### ISSUE TITLE
Cannot type in the Steam Overlay when the async is turned on

### ISSUE THREAD

**Issue by Minztower** [7thbeatgames/adofai#100]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Minztower#6651

### Summary

While the new input system is activated, when I open the steam workshop and type something into the search bar, the site reloads after a few seconds and adofai sounds play in the background when I press keys.

### Version

r100

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Enable the new input system
3. Go into the custom level menu
4. press ESC
5. click "Steam workshop"
6. type something into the search bar

### Expected Behavior

I type something and levels with that name (or similar) show up.

### Observed Behavior

The searched text gets deleted/the site reloads and sounds play in the background. When I press enter it still reloads. This leads to not being able to download custom levels except the ones on the main page (with nothing typed into the search bar).

### Reproduction Rate

100%

### Anything else?

https://user-images.githubusercontent.com/110180060/210096804-72426037-ea96-4903-9ac4-b22888b91a86.mp4

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
