### ISSUE TITLE
It Go VFX Disappearing and Reappearing

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#101]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

Ocassionally on a couple of machines It Go will have VFX disappear and reappear when restarting or playing the level.

Testing has shown it can be caused my a lot of factors, but inconsistently.

From my experimentation:
Dying and restarting by spamming buttons while the VFX are there causes it.
Dying of "overload" causes it.
Getting a lot of Lates or Earlies can cause it.
No matter what when restarting a level without vfx the vfx will reappear when you restart from any method including death.
Backgrounds are just entirely messed up and load seemingly arbitrarily.

### Version

r100 (v2.3.0

### Operating System (OS)

Windows 7-10

### Platform

Steam

### Steps to Reproduce

1. Enter XI-X It Go
2. Restart the level through any means such as dying or pressing restart.
3. Examine the VFX, the goat eyes are a good indicator.

### Expected Behavior

VFX plays consistently.

### Observed Behavior

VFX does not play consistently, sometimes backgrounds disappear, sometimes decorations are entirely missing, etc.

### Reproduction Rate

25%?

**Comment by authop** [comment]
This has been addressed.
