### ISSUE TITLE
On T3-X the coins are invisible with the graphics quality option set to low

### ISSUE THREAD

**Issue by Juandif** [7thbeatgames/adofai#102]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Juandif#2563

### Summary

In the level T3-X from the Neo Cosmos DLC, in the "Collect 3!!" section the coins don't appear when in low graphics quality mode. I imagine this happens in T3-EX too but haven't tested

### Version

v2.3.0/r100

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Set the graphics quality option to low
2. Play T3-X until the Collect 3 section (5th medal) 
3. The coins are not visible

### Expected Behavior

The expected behavior would be for the coins to be visible as the level would be impossible to sightread or beat if you don't remember the usual coin placement.

### Observed Behavior

The coins are invisible when getting to that section.

### Reproduction Rate

100%

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
