### ISSUE TITLE
Play speedtrial without passing normal mode

### ISSUE THREAD

**Issue by KuugenAkikisu** [7thbeatgames/adofai#103]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

argentalgebra@gmail.com , 紲  空現#3508

### Summary

Players can play speedtrial without passing normal mode.
Using "Calibration" twice and a speedtrial as like as easter egg "star4th".

1st, go to a normal level which you want to play in speedtrial. not only -X, but also tutorial. Go to calibration by Esc -> C.
2nd, go to any speedtrial and set speed which you want to play without playing calibration.
3rd, go to calibration on map(don't use Esc -> C), and exit it.
At last, player can play speedtrial without passing normal mode.

### Version

v2.3.0(r100) Windows

### Operating System (OS)

Windows 10 Home 22H2

### Platform

Steam

### Steps to Reproduce

1. wipe save(maybe, not require)
2. enter 1-X(or other levels. ex. 1-1)
3. press Esc -> C to enter calibration
4. press Esc to exit calibration(not require complete calibration).
5. press Esc -> Q to exit level.
6. enter XO-X speedtrial by easter egg "star4th"(or other speedtrials).
7. set speed you want to play.
8. press Esc -> Q to exit level(don't press Esc -> C to enter calibration).
9. go to the portal of calibration(don't use Esc -> C)
10. press Esc to exit calibration.
11. you can play 1-X speedtrial. it speed is the number when set in step 7.
12. pass the level, you can get 2 or 3 lanthanum(Blue and red, or Blue, Yellow and Red)

### Expected Behavior

play XO-X speedtrial.

### Observed Behavior

play 1-X speedtrial.

### Reproduction Rate

100%

### Anything else?

![2023-01-09](https://user-images.githubusercontent.com/122278697/211321504-6ecc346e-c893-46c8-a044-5313261b0e9a.png)
![20230109223937_1](https://user-images.githubusercontent.com/122278697/211321690-51714710-be78-4d12-8eb0-51225f5fa6d4.jpg)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
