### ISSUE TITLE
Practice Mode Speed Settings Intervals Increase

### ISSUE THREAD

**Issue by person2400** [7thbeatgames/adofai#104]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

@Person#7606

### Summary

When in practice mode, when the menu is opened and closed without reloading the level, and opened again, the speed setting will increase by 15% instead of 10%. This number increases by 5% each time the menu is opened and closed without reloading the level. Reloading the level, by changing the speed or duration, resets the increase to 10% at a time.

### Version

v2.3.1 (r101)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Enter any level and enter practice mode.
2. Open the pause menu, and close it without changing speed or duration.
3. Open the pause menu again, and click either arrow to adjust the song speed. It will now increase by increments of 15%. The increment will increase by 5% for every time the menu is opened and closed without reloading the level.

### Expected Behavior

The speed should increase by 10% each time the arrow is pressed.

### Observed Behavior

The speed increases by higher increments, based on how many times the menu is opened without reloading the level.

### Reproduction Rate

100%

### Anything else?

See video showing problem here. Warning: Slight flashing at end.

[https://youtu.be/QzMu0ODEq7U](url)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
