### ISSUE TITLE
ML torches not lighting

### ISSUE THREAD

**Issue by tobyaaaa** [7thbeatgames/adofai#105]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

tobyaaa#7052

### Summary

Recently updated the itch version to play It Go, but in doing so it looks like something broke in La Nuit De Vif: the little flames above the track are no longer lighting up. This seems to have been caused by the update.

### Version

2.3.1 (r101)

### Operating System (OS)

Windows 11

### Platform

itch.io

### Device Info

alienware m17 r3

### Steps to Reproduce

Bug happens consistently in ML-X, in both the normal level and speed trial

### Expected Behavior

At certain points (the first one is at roughly 25%) in the track, there are slots above the track with torches, which (used to) light up with flame as the planets pass.

### Observed Behavior

No animation plays and the torches remain unlit.

### Reproduction Rate

100%

### Anything else?

First image is from ingame for me, the second is a screenshot in a youtube video
![ML_torch](https://user-images.githubusercontent.com/68621460/216773282-0b4d5d84-3c69-406d-ae8d-9ef531710893.png)
![ML_torch_ytscreenshot](https://user-images.githubusercontent.com/68621460/216773357-1881a1b3-2b7e-4e27-9332-fbe3e48784b1.png)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
