### ISSUE TITLE
Game is not proceeding at particular tile

### ISSUE THREAD

**Issue by Runas8128** [7thbeatgames/adofai#106]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Discord tag: Runas#5980

### Summary

Game is not proceeding at particular tile

### Version

v2.3.1 (r101)

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. put `Set Hitsound` event in somewhere (regardless of hitsound type)
2. add midspin to that tile and add another tile (not midspin)
3. put `Set Hitsound` event in the tile you made last

explain with keys > `d 4 h tab d 4`

### Expected Behavior

not stuck at any tile

### Observed Behavior

When playing level planet stops in a particular tile

### Anything else?

I have seen about this bug before, but couldn't find it in issue tracker :(

[Player.log](https://github.com/7thbeatgames/adofai/files/10699395/Player.log)

https://user-images.githubusercontent.com/61743057/217877925-3d0df4ba-9689-4341-84a1-e0429aef23e6.mp4

**Comment by authop** [comment]
Sorry for not responding to this too long.
I can see you applied mods when you recorded the screen. Try to delete all mods and try again to see if the problem persists.

If the problem still happens, please respond with the corresponding .adofai file for reproduction.

**Comment by Runas8128** [comment]
I could reproduce this issue without mods, but I found something weird

When I turned auto off the issue was completely reproduced, but when I turned it on planets went to the next tile while still not orbiting.

I will attach 2 videos below (because I cannot fully describe this issue in English)

[Player.log](https://github.com/7thbeatgames/adofai/files/11132227/Player.log)

https://user-images.githubusercontent.com/61743057/229354039-4442805e-0318-4e0f-9012-39618dcc2bd4.mp4

https://user-images.githubusercontent.com/61743057/229354011-036b34fe-8577-4f9a-b593-7d08d73e774f.mp4

↓↓↓ I changed the extension (.adofai → .txt) ↓↓↓
[level.txt](https://github.com/7thbeatgames/adofai/files/11132237/level.txt)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
