### ISSUE TITLE
'그래픽 품질'을 '낮음'으로 설정 시 T3번째 세계를 정상적으로 플레이할 수 없음

### ISSUE THREAD

**Issue by Strode0496** [7thbeatgames/adofai#107]
### 요약

'그래픽 품질'을 '낮음'으로 설정한 후 T3번째 세계 플레이 시 게임 진행에 중요한 그래픽까지 사라져 정상적인 플레이가 어렵습니다.
If select the 'Graphics Quality' setting to 'Low' and play World T3, all important graphics disappear so making it difficult to play normally.

### 재현 방법

1. 설정에서 '그래픽 품질'을 '낮음'으로 설정합니다.
2. Neo Cosmos DLC T3번째 세계 '힌트 없음!!'을 플레이합니다.
3. '3개를 모으세요!!'에서의 코인이나 '정답은?!'에서의 문제&정답 텍스트, 그리고 '성을 지키세요!!'에서의 운석과 같이 게임 진행에 꼭 필요한 장식 그래픽이 사라져 버립니다.
### 
1. Set 'Graphics Quality' to 'Low' in Settings.
2. Play Neo Cosmos DLC T3 World 'No Hints Here!!'
3. Decoration graphics that are essential for T3 such as coins in 'Collect 3!!', question and answer texts in 'Answer!!', and meteorites in 'Defend the Castle!!' disappear.

### 예측 결과

그래픽 설정을 낮음으로 두더라도 위에서 적은 것과 같은 필수 그래픽들은 사라지지 않고 배경만 단순해지는 등의 요소만 바뀝니다.
Leaving the graphic settings on low doesn't make the essential graphic elements like what I wrote above invisible, only the background simplifies.

### 실제 결과

게임 진행에 꼭 필요한 장식들까지 모두 없어져 버렸습니다. 맨 아래에 상세한 내용들을 첨부하였습니다.
All the decoration graphocs that are essential for the game are gone. Details are attached below.

### 재현율

100%

### 버전 및 플랫폼

- 운영체제: Windows 10
- 게임 플랫폼: Steam
- 게임 버전: v2.3.1 (r101) Public Build
- ~~디바이스 이름 (모바일):~~

### 그 외

구간별 동영상 자료들
Videos for each mini-game section

[삼각형.webm](https://user-images.githubusercontent.com/79904194/218011635-49c860f5-26c7-45f6-8ae5-6018f3b41d38.webm)

**까다로운 삼각형!! / Tricky Triangles!!**
배경의 무늬가 없어졌습니다. 이 현상은 그래픽 설정이 높음일 때와 모바일 버전에서도 나타나는 것 같습니다.
The background pattern is gone. This seems to happen when graphics settings are high and also on the mobile version.

[코인안보임.webm](https://user-images.githubusercontent.com/79904194/218012388-09dee5c4-2663-4af5-80cd-b180b93e03ca.webm)

**3개를 모으세요!! / Collect 3!!**
코인이 보이지 않습니다.
Coins are not visible.

[워프타일안보임.webm](https://user-images.githubusercontent.com/79904194/218013001-3857ae1b-7c98-40b2-b0dd-7480e089d282.webm)

**순간이동!! / Warp Tiles!!**
워프 타일이 보이지 않습니다.
Warp tiles are not visible.

[문제참쉽죠.webm](https://user-images.githubusercontent.com/79904194/218013249-2ed61865-4495-4245-a822-4a44f4d4065d.webm)

[문제참쉽죠둘.webm](https://user-images.githubusercontent.com/79904194/218013277-2a7e100a-36f9-4eeb-bf5f-f504b18b4c02.webm)

**정답은?! & 정답은??!! / Answer!! & Answer!! Again!!**
문제와 정답 텍스트, 그리고 가짜 길 장식이 보이지 않습니다. 
Question, answer text, and fake tile decorations are not visible.

[내가운석을막는건가.webm](https://user-images.githubusercontent.com/79904194/218014222-23c6af11-b268-4b50-9051-999eee9c562b.webm)

**성을 지키세요!! / Defend the Castle!!**
뜻하지 않은 암기 기믹을 즐기게 됩니다.
It has been changed to only those who have cleared T3 lol

[안개다털렸죠.webm](https://user-images.githubusercontent.com/79904194/218014476-3908b81b-0e5a-49b6-96ab-9fcd4e5c403d.webm)

**안개 조심!! / Fog!!**
안개를 조심할 필요가 없어졌습니다.
No need to worry about fog.

[숫자안보임.webm](https://user-images.githubusercontent.com/79904194/218013846-50f26647-4f62-4485-a2e6-ffcf03ea00b9.webm)

**들키지 마세요!! / Avoid Being Spotted!!**
숫자 표시가 보이지 않습니다.
The number display is not visible.

[이거의도한거냐.webm](https://user-images.githubusercontent.com/79904194/218014544-1277b662-97fe-434f-9bf8-71fff84e39d7.webm)

**거의 다 왔어요!! 집중!! / Almost there!! Don't get distracted!!**
이건.. 혹시 의도한 건가요?
Was this intentional?

[마지막구간.webm](https://user-images.githubusercontent.com/79904194/218014684-703dc245-c239-483b-a593-db6cd545be05.webm)

**이제 막바지입니다!!! / Keep going! Final stretch!!**
'순간이동!!', '성을 지키세요!!'에서의 버그가 여기에도 마찬가지로 있으며, 정사각형 타일 4개가 날아오는 구간에서 날아오는 애니메이션 없이 바로 생겨 버립니다.
The bugs in 'Warp Tiles!!' and 'Defend the Castle!!' are here as well, and the 4 tiles appear right away without any flying animation.

그래픽 설정 낮음 모드도 신경 좀 써 주세요 ;-;
Please also pay attention to low graphics settings :(

**Comment by authop** [comment]
개발자 빌드에서 해당 문제가 해결되었습니다.
This has been resolved on the dev build.
