### ISSUE TITLE
Volume settings not working in DLC

### ISSUE THREAD

**Issue by TheDoginator** [7thbeatgames/adofai#108]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

TheDoginator#5868

### Summary

The music volume and hitsound volume settings have no effect in the Neo Cosmos levels and level select, the music and hitsounds play at full volume regardless of what the settings are set to. Main volume, SFX volume and interface volume seem to work as intended.

### Version

v2.3.1 (r101)

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. Turn down the Music Volume and/or Hitsound Volume settings
2. Enter the Neo Cosmos level select or a Neo Cosmos level
3. The music/hitsounds will play at full volume regardless of what you set the volume settings to.

### Expected Behavior

The music and hitsounds should play at a lower volume when their volume settings are turned down, and should not play at all when the volume settings are set to 0.

### Observed Behavior

The music and hitsounds play as they would if the volume settings were set to 10. Turning down the main volume does make the music and hitsounds play quieter as expected. In levels other than the Neo Cosmos levels, and in the main non-Neo Cosmos level select screen, the music volume and hitsound volume settings work as expected.

### Reproduction Rate

100%

**Comment by joshuamartin25** [comment]
I think this is related, if you start a practice run and finish it with 3 planet segments after, you can still hear the sfx that plays when changing the number of planets when that would happen.

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
