### ISSUE TITLE
Sometimes, the planets go past the next tile (kinda hard to describe, just watch video)

### ISSUE THREAD

**Issue by stuff14** [7thbeatgames/adofai#109]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Email: jiwoongum117@gmail.com

### Summary

Occasionally, while I'm playing adofai, this happens:
https://user-images.githubusercontent.com/70532664/220823503-983c545a-7599-458c-8c16-eb9f65f46f69.mov
(Sorry for very short clip, GitHub limits file size to 10MB)

Here's a bit longer clip, from google drive, You might have to download the video if it doesn't play:
https://drive.google.com/file/d/1FMmpdAASjocOQG-FCtAVtVXc9yR10bvA/view?usp=share_link

The planets go past the tile they're supposed to hit next. At faster speeds, it doesn't let you hit the next tile, and you die. 

When this happens, usually the game starts to log keys like esc as playing keys, and you can't open the menu. 

### Version

v2.3.1 (r101)

### Operating System (OS)

Mac OS Ventura 13.0

### Platform

Steam

### Device Info

Macbook M2

### Steps to Reproduce

Not really any steps to reproduce. It can happen anytime. Once adofai was like this as soon as I launched the game.

### Expected Behavior

The planets aren't supposed to go past the tiles.

### Observed Behavior

That planets go past the tiles, but the "perfect" tag still shows up.

### Reproduction Rate

uncommon

### Anything else?

This issue started quite a while ago, but it couldn't have been bothered enough to submit this bug. (November/December 2022 sometime around those months). This bug also happens in Intal macs (I used to play adofai on an intel mac, but now I have M2). This also happens on my brother's M1 mac.

**Comment by authop** [comment]
I suspect this happens when you have an extreme offset. I can see the planet animation goes beyond the sweet spot but counts as perfect. This would not be the problem with a low BPM, but this count towards 'Very Late' if the rotation is fast enough.

Have you tried to calibrate the offset by chance?

**Comment by stuff14** [comment]
My calibration is set to 66ms and I have been using that setting for quite a while. I'm pretty sure that's the correct calibration as I have cleared faster levels like "The limit does not exist", "First town of this journey", and "Megamix" to name a few.

Here's what it normally looks when the bug isn't happening:
https://drive.google.com/file/d/12JBTxDpiHguSmdahuK9VR-HajKQolB3r/view?usp=sharing

(again, you might have to download the video if it's not playing)

**Comment by stuff14** [comment]
If it was because the calibration was off, the "late" tag should be appearing as the planet has gone way past the "perfect" timing window. However, in the video, the "perfect" tag still appears, even though the angle when I hit the next tile is way outside the perfect timing window.

**Comment by stuff14** [comment]
When this happens, another that that can occur is that the game doesn't let me go to the next tile at all and the judgment text starts spinning really fast:
https://drive.google.com/file/d/1D4sSnEv5uVHJzc9jqnitM_NiMoiuHkGm/view?usp=sharing

**Comment by joshuamartin25** [comment]
Hmmm, this seems like an Async Input issue. If you have Async Input turned on right now, try turning it off and see if you still get the glitch.

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
