### ISSUE TITLE
Add an option to the Move Track event to set movements relative to either the original position of the tile or its current position

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#11]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Using the Position Track event makes it so the starting position of Move Track events is calculated from the place the track got moved to instead of being treated as if it was still connected to the rest of the track. While this is fine most of the time, under some circumstances it can be really uncomfortable and make simple movements you could copypaste into way more tiresome ones that require you to change the value of each individual event

Example:

These are the tiles these track groups are offset by:
![image](https://user-images.githubusercontent.com/96384208/182438007-f43e483a-f19e-47f0-aad9-6f4bfd825768.png)

This is the movement I'm making, which moves the next tiles down by 0.25 tiles each beat:
https://user-images.githubusercontent.com/96384208/182439337-d3976f60-460a-41a0-b9b3-26866d994110.mp4
For doing this, instead of being able to copy an event with "Position: -0.25 Y" every beat (or using the Repeat Events event for it), I have to move the next tiles by -0.25 the first beat, -0.5 the next, etc.

### Suggestion / Solution

Add an option to the Move Track event to set movements relative to either the original position of the tile or its current position, similarly to how camera movements also have different settings they can be set relative to

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
