### ISSUE TITLE
Adding rotation relevant to the pivot, to move decorations with extreme parallaxes

### ISSUE THREAD

**Issue by authop** [7thbeatgames/adofai#110]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

This is the translation of this suggestion: https://discord.com/channels/959280727671836682/1000488716642553966/1084119101649203300

Making connections between decoration movements and tile events are inconvenient. If I want to fix the decoration on the screen, its parallax needs to be set to 100. In this state, decoration position change is only possible by the pivot. However, the pivot cannot be moved with 'Move Decoration'.

### Suggestion / Solution

Is it possible to allow decorations to rotate in orbit around a certain decoration pivot? (to implement joint movement)

### Alternatives & Workarounds

- To fix the decoration on the screen and move it according to the absolute value, I need to set the parallax to 99.9-99.99 and set move. This move requires 1000+ tiles, so it is hard to calculate.
- Alternatively, I create another duplicated decoration with a different pivot.

**Comment by wjdgustn** [comment]
parallax offset and pivot offset move was added!
