### ISSUE TITLE
Dragging angle offset to 0 degrees sets it to 360

### ISSUE THREAD

**Issue by Rikri4009** [7thbeatgames/adofai#111]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

Sometimes, when dragging an event's angle offset to 0 degrees, it gets set to 360 instead.

### Version

v2.4.3

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. After having the editor open for a while, drag any event's angle offset to 0 degrees

### Expected Behavior

It gets set to 0 degrees

### Observed Behavior

After a certain point, it gets set to 360 degrees - it's unclear what exactly the trigger is, however

### Reproduction Rate

Generally, this bug crops up after having worked on any level for a while (30+ minutes)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
