### ISSUE TITLE
XI-X zooms in at the dragon

### ISSUE THREAD

**Issue by Tortilotl** [7thbeatgames/adofai#113]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

BurritoMaster217#1961 on Discord

### Summary

In Xi-X It Go, the camera zooms in when you reach the dragon part (about 77%) and stays zoomed upon fail, only being undone by restarting or quitting

### Version

v2.4.5 (r107)

### Operating System (OS)

iOS 16.1.2

### Platform

App Store

### Device Info

iPhone Cs Max

### Steps to Reproduce

1. Play It Go
2. Get to 77% in the chart
3. See bugged zoom

### Expected Behavior

No zoom

### Observed Behavior

Camera zooms in, obscuring track in front

### Reproduction Rate

100%

### Anything else?

Images show the zoomed camera effect
![A7FD5749-4CE6-4630-ADF1-AF1A9AA231C5](https://user-images.githubusercontent.com/130107691/230512793-b4704394-6a54-40da-929f-0bd9f3982630.png)
![2B6976CF-395E-4D32-A546-209675E619CA](https://user-images.githubusercontent.com/130107691/230512821-da011fd8-7cdd-42e4-b193-a1490d1f21e4.png)
![885FBCA5-B49A-4FB9-B76D-57298C414D87](https://user-images.githubusercontent.com/130107691/230512834-7cc41f07-1945-45ec-91f3-def7181dcb18.png)
![A3085A9E-2EA5-4CB3-9E2B-FE1193157DD1](https://user-images.githubusercontent.com/130107691/230512836-0a3bb2c3-f554-4ed6-b0ad-8d4bb0dbef75.png)

**Comment by authop** [comment]
It has been resolved!
