### ISSUE TITLE
planet orbits seems to get more jittery as time goes on

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#114]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

sometimes when i've been playing adofai, the planet orbits felt a bit stuttery, like they're orbiting at 30fps while everything else moves at the usual 60

### Version

v2.4.4 (Linux)

### Operating System (OS)

Linux (KDE neon 5.27)

### Platform

Steam

### Device Info

Desktop

### Steps to Reproduce

1. play multiple levels in one session , i think ?

### Expected Behavior

planets orbit smoothly

### Observed Behavior

planet orbits appear stuttery, and sometimes uneven

### Reproduction Rate

sometimes ??

### Anything else?

i feel like i've only begun to notice this after moving to linux - it's been around for a little while ! the effects seem tame near the start of a session but it feels like it worsens as you play, i think

**Comment by bugbard-cryptid** [comment]
(sorry for adding this in a reply instead of the original issue - obs is weird on wayland right now and i had to login on x11 to record this = = this isnt the best quality, but going frame by frame makes the uneven orbit clearer ;

https://user-images.githubusercontent.com/61643906/233868234-60353dcc-fd8c-4dcf-b1da-6156c1e3e46b.mp4

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
