### ISSUE TITLE
opening the CLS searchbox with arrow keys and typing will drop the first letter you type

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#117]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

it seems like the search box isnt selected when you press the left arrow, so when you start typing, you first letter selects the search box instead of typing in it, failing to type the first letter

### Version

v2.5.0 (Linux)

### Operating System (OS)

KDE neon 5.27

### Platform

Steam

### Steps to Reproduce

1. on the CLS, press the left arrow to bring up the search box
2. type the name of a level

### Expected Behavior

letters will immediately start being typed

### Observed Behavior

the first letter instead _selects_ the searchbox, then the rest of the letters afterward are typed properly, dropping the first letter you typed

### Reproduction Rate

100%

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
