### ISSUE TITLE
2.5.0 update breaks levels in level editor

### ISSUE THREAD

**Issue by stuff14** [7thbeatgames/adofai#118]
### Please Check

- [x] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Email: jiwoongum117@gmail.com

### Summary

Levels played in the level editor are broken as songs and decorations do not load properly, even though they exist in the level file.

### Version

v2.5.0

### Operating System (OS)

Mac OS Ventura 13.4

### Platform

Steam

### Device Info

Macbook M2

### Steps to Reproduce

1. Load any level in the level editor
2. All decorations, background image, and songs are not loaded properly

### Expected Behavior

the song should play properly, and the decorations/background should also load properly.

### Observed Behavior

The song is not played, and if a previous level was loaded, the song from that level starts playing. Decorations and background do not load either.
This issue can be manually solved however:
1. re-assign images to decorations or background / re-assign ogg or wav file to level song
2. exit the level editor
3. enter the level editor
4. load the level again

This then loads all the decorations and songs properly. 

### Reproduction Rate

100% Every level I had in the level editor before the 2.5.0 update is affected by this bug

### Anything else?

video of the bug:
https://drive.google.com/file/d/1WOxBDSOsM9aJWFoVsO0zZqyHTyZG6r2p/view?usp=sharing
In this video, I had already loaded Fallen Symphony in the level editor and reassigned the bg and wav files, so it loaded properly.  Fallen Symphony was also previously affected by the same bug.

video of how to manually solve the issue:
https://drive.google.com/file/d/1ea1UZAKVs96YESV3ITZGoKpLw7YhYPKm/view?usp=sharing

**Comment by authop** [comment]
It was reproducible on my machine. Forwarding this to giacomo.

**Comment by authop** [comment]
Hello! ADOFAI needs disk access to read/write your storage!
Please note that if you use the Steam version, the app icon on the Launchpad is barely a shortcut!

1.  Go to System Preferences -> Privacy & Security -> Full Disk Access. Click the + icon at the bottom of the list.
2. You need to find ADOFAI's install location. If you are using Steam and didn't change the install location beforehand, it should be at `/Users/[your username]/Library/Application Support/Steam/steamapps/common/A Dance of Fire and Ice/`. If the Finder hides the Library folder, press `commend-shift-. (dot)` on the Finder to reveal it.
3. Double-click `ADanceOfFireAndIce.app` and turn the access on for ADOFAI.

I will write a detailed guideline in our Knowledge Base.

**Comment by authop** [comment]
A window should appear asking for permission to access the folder, but this is broken right now. We are looking for a fix.

**Comment by stuff14** [comment]
ty, manually giving adofai full disc access solved the issue.

**Comment by authop** [comment]
Please note that you should temporarily use it! We do not recommend giving full disk access to apps you don't trust.
After the fix, we recommend turning off full disk access for ADOFAI and turning on the "Files & Folders" permission instead.

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
