### ISSUE TITLE
performing a multipress on level select gem tiles often causes the planets to be left behind

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#119]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

gwoobeast (discord)

### Summary

if you hit 2 keys at once on a gem tile (one without a screen transition - this won't happen on the gem tile that leads to the bonus / MD levels), the gem tile will move without you, and the camera may go with it, leaving you offscreen usually. trying to use fast travel keys to get to the gem tile and using it again will cause strange misalignment issues

### Version

v2.5.0 (Linux)

### Operating System (OS)

KDE neon 5.27

### Platform

Steam

### Steps to Reproduce

1. navigate to a gem tile on the main menu (one _without_ a screen transition, like the MD island / bonus island both have)
2. press 2 keys at the same time, when a planet is over the gem

### Expected Behavior

the gem tile stays put

### Observed Behavior

the gem tile moves away without the player, and the camera follows

### Reproduction Rate

100%

### Anything else?

videos nd screenshots ,,,

![image](https://github.com/7thbeatgames/adofai/assets/61643906/cdd6764b-8e5c-454d-9128-65bdda04262d)

https://github.com/7thbeatgames/adofai/assets/61643906/31b7115e-0143-4f74-91b0-7c061f816491

**Comment by bugbard-cryptid** [comment]
this appears to be fixed ...! multipressing on gem tiles now seems to prevent any input until you are safely across the gap, which prevents you from stepping on and off like this.

**Comment by wjdgustn** [comment]
oh yes it was fixed 5 month ago
