### ISSUE TITLE
Make No-fail clears without any misses show up as level completions in the CLS

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#12]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Despite being actual clears, clearing a level with No-fail without any fails will not have any effect on your completion status in the CLS

### Suggestion / Solution

Make No-fail clears without any misses show up as level completions in the CLS

**Comment by CrackThrough** [comment]
Done! Will be released next version.
