### ISSUE TITLE
레벨 중간에 카운트다운 틱 변경

### ISSUE THREAD

**Issue by Sangmin23** [7thbeatgames/adofai#120]
### 문제점

게임 오버 뒤 체크포인트에서 다시 시작할 때 곡의 박자가 바뀌어도 (예시 : 4/4 박자 -> 7/8 박자, 4/4 박자 -> 3/4 박자 등) 카운트다운 틱은 바뀌지 않아서 불편합니다.

### 제안 및 해결 방법

"체크포인트 추가" 이벤트에 "카운트다운 틱 변경" 기능 추가, 그 체크포인트에서 시작할 때 적용하기.

### 대체 방안

현재 없음

### 그 외

설정 활성화/비활성화 가능

**Comment by authop** [comment]
Hello!

This is scheduled on our future plans! We'll inform you on our news channels when it becomes available.

Thank you!
