### ISSUE TITLE
Asynchronous input turning itself off, not working

### ISSUE THREAD

**Issue by renoxtv** [7thbeatgames/adofai#122]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

email: guyguygftyfty@gmail.com

### Summary

Asynchronous input is turned OFF whenever I launch the game. Turning it on makes no effect and upon switching menus (i mean going to custom maps, back and forth) it turns itself back off. This issue started happening 2-3 days ago, I did not do anything prior that. I can only play with asynchronous input on, or else it will detect multipressing constantly if i do 4-key rolls (or more)

### Version

v2.5.0 r110

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

Lenovo ThinkPad T480s

### Steps to Reproduce

1. Open ADOFAI
2. Settings > Asynchronous input > ON
3. Go to another menu (custom maps for example)
4. Check asynchronous input again in settings

### Expected Behavior

Asynchronous input remains ON and is effective

### Observed Behavior

Asynchronous input is back to OFF and is ineffective even if i turn it back on

### Reproduction Rate

100%

**Comment by pikokr** [comment]
It was already fixed, but it was not released yet.
This will be fixed on next release
