### ISSUE TITLE
add "Decoration" option under "Relative to" dropdowns

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#123]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

i was playing with object decorations, making a square that unravels in front of you for fun, but i found it sort of confusing to juggle the pivot offsets + positions of the objects to make it look correct

### Suggestion / Solution

add an option to position a decoration relative to another decoration! that way, all the decorations can have the same pivot offset to remain connected to each other when rotated

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
