### ISSUE TITLE
Planets freeze at random points in level

### ISSUE THREAD

**Issue by meawplex-plus** [7thbeatgames/adofai#124]
### Please Check

- [x] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

(Email) meawplex.plus@gmail.com

### Summary

When I open some levels in the level editor, the planets freeze at random angles on random tiles but the hitsound audio keeps going past the freezing point. When in this state, I cannot move the planets at all and any keypresses show the "Early" or "Late" signals.

### Version

v2.5.0

### Operating System (OS)

macOS Ventura (13.4) Apple M1/ARM64

### Platform

Steam

### Device Info

13-inch MacBook Pro, 2020 model

### Steps to Reproduce

<details>
<summary>(AS YET UNCERTAIN OF THE CAUSE. I WILL TRY TO EXPLAIN WHAT I DID AS BEST I CAN.)</summary>

1. Open the level editor and make a new level.
2. Add a song and configure the offset.
3. Customize other properties in the start menu.
4. Add some track and effects.
5. Play the level (autoplay or normal mode).
6. Observe the planets randomly halt (while the hitsounds continue going if in autoplay).
</details>

### Expected Behavior

I expected the planets to continue their movement path.

### Observed Behavior

The planets halted at a random tile.

### Reproduction Rate

100% for every level I have tested.

### Anything else?

<details>
<summary>Player.log and Player-prev.log</summary>
<a href="https://github.com/7thbeatgames/adofai/files/12709996/Player.log">Player.log</a><br/>
<a href="https://github.com/7thbeatgames/adofai/files/12710009/Player-prev.log">Player-prev.log</a>
</details>
<details>
<summary>Videos of incident</summary>
<a href="https://drive.google.com/file/d/1ZKvab9QeIPp0PCRgO5EBph8b4aqsCiYZ/view?usp=sharing">Without Autoplay</a><br/>
<a href="https://drive.google.com/file/d/1UKhHjOKF43Oji6k-mQy1dy9yQ_Ox4i45/view?usp=sharing">With Autoplay</a>
</details>

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!

**Comment by wolfplay013** [comment]
999 degree angles are midspins
