### ISSUE TITLE
Running ADOFAI 2.6.0 on macOS through Rosetta breaks the audio

### ISSUE THREAD

**Issue by Wide0125** [7thbeatgames/adofai#125]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [x] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wide0125(Discord)

### Summary

I've made a post of this same bug on the discord server already, however I haven't gotten any responses even after a couple of days, so I'm posting here to see if I can get any sort of response.

Hi, so the recent 2.6.0 update broke the sound for ADOFAI. This seems to only occur when the game is run through rosetta (I run ADOFAI through rosetta because Unity Mod Manager doesn't support apple silicon) and the game has no issues when run natively. This issue seems to occur regardless of mods, the only trigger seems to be running it through rosetta. I previously made a post on this bug, however restarting my computer seemed to fix the issue, so I thought that was that. However the issue returned, and it seems that every time you restart the game the issue seems resolved at first, but comes back slowly, getting worse and worse. It sometimes gets so bad that the game becomes unplayable at times, and also affects other applications. such as chrome (i.e. any youtube videos played will have the same audio issues). Closing the game fixes this, other applications return to normal.

On a side note, ADOFAI doesn't seem to support HDR when run natively, but does support HDR when run through Rosetta, strange.

### Version

2.6.0

### Operating System (OS)

macOS Sonoma (M1 Pro)

### Platform

Steam

### Device Info

Macbook Pro (2021, 14 inch)

### Steps to Reproduce

1. Install ADOFAI through steam on an apple silicon mac
2. On steam, go to "Browse local files"
3. On the finder window that pops up. right click on "ADanceOfFireAndIce.app" and click "Get Info"
4. Check "Open using Rosetta", and launch the game through steam
5. Play levels for a couple minutes

### Expected Behavior

I expected ADOFAI to play the audio properly for levels.

### Observed Behavior

ADOFAI played glitchy audio.

### Reproduction Rate

100%

### Anything else?

https://github.com/7thbeatgames/adofai/assets/95921629/8596800d-468c-4619-bfdf-3c2a51dcc63a

[Player.log](https://github.com/7thbeatgames/adofai/files/13226981/Player.log)
Log file of when the video was taken

**Comment by Wide0125** [comment]
still occurs in 2.6.1

**Comment by authop** [comment]
Using Rosetta means the emulator is working along with it. Performance may get hit as you run the game on a virtual machine (kind of).

Running x86 code with Rosetta appears to hit 20% performance in the benchmark, but it may hit more for visual-intensive tasks. If lowering the game's graphics settings, such as resolution, fixes it, that's most likely the cause.
