### ISSUE TITLE
Game breaks discord streams 

### ISSUE THREAD

**Issue by Ryvthm** [7thbeatgames/adofai#127]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Discord: noxthetoaster#0

### Summary

When streaming the game on discord, the stream often lags and becomes unstable. I've ran through all possible troubleshooting techniques and verified that all of my equipment is working perfectly fine. I believe the issue to be caused by the fact that when you launch most games, discord injects a DLL which allows you to press a hotkey to access a mini version of the app. I believe this feature also gives the user the ability to stream content from the game easier.  The game however, does not seem to allow discord to attach itself to the program either due to the fact that it is being prevented somehow, or that discord simply does not recognize the program.

### Version

Latest release

### Operating System (OS)

Windows 11

### Platform

Steam

### Device Info

PC (Ryzen 5, RTX 3050)

### Steps to Reproduce

Not sure if others have the same problem, but for me:
Step 1 - Simply start a discord stream
Result - The stream connection is unstable and lags every few seconds freezing up or sometimes pausing.

### Expected Behavior

The stream works perfectly fine and all is good in the world.

### Observed Behavior

The stream is buggy like mentioned before.

### Reproduction Rate

100%

### Anything else?

Honestly not sure what sort of screenshot to show here, it's just that streaming is laggy.

**Comment by Ryvthm** [comment]
If useful, my wifi runs pretty stable at around 150 mbps download and 50 mbps upload.

**Comment by authop** [comment]
I don't know if it is the game's fault because Discord is heavily involved. If the game worked perfectly fine after injecting Discord overlay, the problem would persist on Discord. I'm closing this because of this.
