### ISSUE TITLE
Toggleable tile icons for Paused Beats and AutoPlay Tiles

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#13]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Without any external methods that indicate them, it's impossible to know whether a tile will be a pause tile or an auto tile and while Neo Cosmos uses gems to indicate pause tiles, many people in the community still don't use them

### Suggestion / Solution

Add toggleable tile icons for Paused Beats and AutoPlay Tiles so no external method is needed to indicate them and make them be toggled on by default, since there's people that may not know indication is needed to keep the level fair. The pause tile icon could just be a simple pause icon and auto tiles could have Otto on them

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
