### ISSUE TITLE
Show Bookmarks and/or Checkpoints in the Practice Mode menu

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#14]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Using the practice mode tile search bar can often be uncomfortable and you often end up on a different tile than where you'd want to be, specially on mobile

### Suggestion / Solution

Show Bookmarks and/or Checkpoints in the Practice Mode menu so the starts to different sections can be marked by the level creator and the player can easily choose where to start from. I added Bookmarks to this suggestion so levels without checkpoints can also have different sections be marked so the player can choose them. 

If this were to be added, I'd also like to see bookmarks added to main game levels so players can choose different sections more easily, which would be specially great for mobile players.

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
