### ISSUE TITLE
More decoration depth options

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#15]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

It is currently impossible to have a decoration above the track but below the planets (example shown below)
![image](https://user-images.githubusercontent.com/96384208/182443823-34f02f44-fb20-4eae-bf64-48aa80a87ed0.png)
![image](https://user-images.githubusercontent.com/96384208/182443831-5289197e-8b3f-4df2-a24a-d234d763804d.png)

### Suggestion / Solution

Add more decoration depth options so it's possible

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
