### ISSUE TITLE
Indicators for progress on unlockables

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#16]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

There's many things in the game that you won't know about unless you ask people online about it, and while that's fine for some things, like hidden planet colors, not knowing about unlockables seems like a bit too much, specially when the criteria for unlocking some things doesn't apply in other places (speed trials for worlds 1-6 unlock B-X, speed trials for worlds 7-12 unlock nothing)

### Suggestion / Solution

Add indicators for progress on unlockables so people know if there's anything they can unlock or if they're done with main game content

### Demo & Mockup

Clearing 6-X could make B-X's entry portal appear outlined, and when you step on it it could tell you the criteria needed to unlock it. Same goes for B-X and Crown Island's gem and the Muse Dash levels and MO-X's level icon. Maybe the same could be done for planet colors so you can know about the criteria to unlock them too

**Comment by authop** [comment]
Better unlock progression indicator is planned!
