### ISSUE TITLE
Rename "Perfects Only Mode" to "Restrict Judgments" and add "Pure Perfects Only" as an option to it

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#17]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

An option so only Perfects are allowed without needing any mods would be great, since there's many people that like to go for Pure Perfects

### Suggestion / Solution

Rename "Perfects Only Mode" to "Restrict Judgments" and add "Pure Perfects Only" as an option to it. If this got added, "Perfects Only Mode" should probably get renamed to "Restrict Judgments" and instead of a toggle, it'd have three options: "No restriction", "Perfects Only" and "Pure Perfects Only"

If the suggestion doesn't get added, I'd still want the name of "Perfects Only Mode" to be changed because some people have mistook it for a purely aesthetical setting, since it visually changes tiles on EPerfects and LPerfects

**Comment by wjdgustn** [comment]
Done!
https://user-images.githubusercontent.com/34962071/233441165-4566b29d-7a5d-4adc-a694-43b7faf5abb6.mp4
