### ISSUE TITLE
Make the Multiplanet event something that's not an input field

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#18]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Multiplanet doesn't need an input field since there's only two states it can be in, two planet mode or three planet mode

### Suggestion / Solution

Either make the Multiplanet event a toggleable event like Twirls and Checkpoints since there's only two states it can ever be in, or make it so there's only two options you can choose through buttons if making toggleable is impossible for whatever reason or if you're planning on adding even more planets in the future

### Demo & Mockup

Example of buttons for choosing Multiplanet options (made by Wolfplay):
![image](https://user-images.githubusercontent.com/96384208/182449860-4bfa9f43-9489-4605-9e58-fef791e5a34c.png)

**Comment by authop** [comment]
It will be togglable in the future release.
