### ISSUE TITLE
Add a keybind that rotates the selected track by 60 degrees to make three planet mode charting easier

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#19]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Using regular flipping and rotating keybinds when you change the track doesn't always apply for three planet mode since you often have to rotate the track by some multiple of 60

### Suggestion / Solution

Add a keybind that rotates the selected track by 60 degrees to make three planet mode charting easier

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
