### ISSUE TITLE
Miss indicators at the wrong spot

### ISSUE THREAD

**Issue by Minztower** [7thbeatgames/adofai#2]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Minztower#6651

### Summary

When you have a pause tile where it switches from 3 to 2 balls and one of the original 2 balls gets destroyed, the miss/overload indicators are at the wrong spot.

### Version

v2.0.3 (r92)

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

Lenovo Legion 5

### Steps to Reproduce

1. make a straight line where the first tile switches to 3 balls
2. make the 5th tile (others work as well) a pause tile with a 3 to 2 ball switch
3. play the level and press to early a few times after the pause tile

### Expected Behavior

The miss indicators show at the spot where you pressed too early (where the planet was at that point

https://user-images.githubusercontent.com/110180060/181525067-5bb667eb-d77a-4865-b12f-349cf0a5723a.mp4

### Observed Behavior

The miss indicators showed somewhere around the pause tile

https://user-images.githubusercontent.com/110180060/181525497-bec21b4f-305f-41f8-a225-af5cae41323e.mp4

### Reproduction Rate

100%

**Comment by authop** [comment]
It has been fixed on the dev build. This will be addressed in the future release.
