### ISSUE TITLE
Make No-fail accesible through Practice Mode

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#20]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Having No-fail in practice mode could help with learning the level, also people have suggested in the past wanting to play through levels again for fun with No-fail and putting it behind practice mode would will two birds with one stone

### Suggestion / Solution

Make No-fail accesible through Practice Mode as a setting you can turn on next to the speed selector

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
