### ISSUE TITLE
Add a subtitle to MO-X's Speed Trial in the menu that says "1.0x (no checkpoints)"

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#21]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

I've seen some people confused about the lack of subtitle for MO-X because XO-X has one

### Suggestion / Solution

Add a subtitle to MO-X's Speed Trial in the menu that says "1.0x (no checkpoints)"

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
