### ISSUE TITLE
Make tile icons not be affected by positive tile opacity

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#22]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Positive tile opacity is an interesting feature to play around with but it makes tile icons look bad, when it wasn't the case with Sprite tiles

### Suggestion / Solution

Make tile icons not be affected by positive tile opacity so people can use it again

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
