### ISSUE TITLE
Random level option in the CLS

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#23]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

RD has it and it'd be nice to have in ADOFAI too

### Suggestion / Solution

Add a random level option in the CLS, both by pressing R and as a choosable option in the CLS Search menu

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
