### ISSUE TITLE
Add a "Date Added" option to the level order options in the CLS Search menu

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#24]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Levels in the CLS only show at the top of the level list as newly added the first time you open the CLS, once you leave or enter a level and then exit back to the CLS, they won't be marked as newly added anymore, making it difficult to find levels you've just added without the usage of some external list to keep track of them

### Suggestion / Solution

Add a "Date Added" option to the level order options in the CLS Search menu

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
