### ISSUE TITLE
Achievement(s) for Muse Dash island completion

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#25]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

RD got them, I don't see why ADOFAI shouldn't

### Suggestion / Solution

Achievement(s) for Muse Dash island completion

### Note

This is a bit unrelated but even though it's been said that no achievements would be added for extra content to not make people's completionist take over and make them play through something they may not want to play, I still believe adding achievements for Xtra and Crown island completion (when they're full) would be good, specially since getting all achievements requires the DLC now anyways which has some difficult achievements. I'm dropping this here because I don't want to make a whole suggestion out of it at the moment

**Comment by authop** [comment]
We didn't add achievements for extra levels because we thought it was too difficult compared with regular worlds, and we didn't want to force clears to 100% completionist. However, the average skill has improved overall.

I think it is time to discuss this with the team, so I'll put this on our bulletin board.

**Comment by prodzpod** [comment]
Shouldn't this issue be closed now that the achievements are in?

**Comment by authop** [comment]
I completly forgot about this, closing.
