### ISSUE TITLE
Speed Trial aims for Featured Levels

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#26]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Many creators have wanted to have Speed Trial aims for their levels but it's been rejected since it could be abused and be made into really high speeds which would be unfair for the player. Since Featured Levels are chosen by the devs, creators could suggest a value for the speed trial and the devs could quickly review it and give it a pass or tweak it. This way creators can fulfill that dream of theirs and it gives Featured Levels a bit more replayability

### Suggestion / Solution

Speed Trial aims for Featured Levels

**Comment by wjdgustn** [comment]
added!
