### ISSUE TITLE
Make the tile extend animation in RJ-X show more tiles

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#27]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

It's a bit hard to react to what's coming in the sections in RJ-X that use extending tile animations, specially since you need to think about needing one or two keys

### Suggestion / Solution

Make the tile extend animation in RJ-X show more tiles

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
