### ISSUE TITLE
(alpha) MN-X doesn't show its lofi background when "Graphics Quality" is set to "Low"

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#28]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Econ#5853

### Summary

Instead of its intended background, MN-X only displays a solid color on Low quality throughout the entire level

### Version

v2.0.5 (r94), Alpha Branch

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Set Graphics Quality to Low
2. Enter MN-X

### Expected Behavior

I expected MN-X to have its lofi background

### Observed Behavior

It did not

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
