### ISSUE TITLE
Add a visible "Checkpoint count" before entering a level both in the main game and the CLS

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#29]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

People who play the game for the first time may expect more checkpoints on a level with only one checkpoint. Also it'd just be neat to know before going in

### Suggestion / Solution

Add a visible "Checkpoint count" before entering a level both in the main game and the CLS that goes away once you've cleared the level

**Comment by authop** [comment]
After we discussed this, we agreed that its weight is relatively low compared with other information, and the current UI is overwhelming with text already. I personally think it can be addressed when we switch those to icons, but that's not what we seek at this stage.
