### ISSUE TITLE
MO-X planets disappearing

### ISSUE THREAD

**Issue by purplpasta** [7thbeatgames/adofai#3]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

purplpasta#9136

### Summary

When playing MO-X or the MO-X Speed Triall, the very first tile makes the planet disappear (move offscreen?) for one frame. When hitting the tile very late or not at all, both planets will vanish until the attempt is over. Additionally, some tiles will appear for 1 frame.

When both planets disappear, the timing indicators ("Perfect", "Late", ...) appear near the bottom left corner.

### Version

v2.0.3 (r92)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Open MO-X or its speed trial
2. Touching the first tile will cause one planet to vanish for a frame
3. Being very late will cause the planets to vanish completely

### Expected Behavior

None of the planets vanish

### Observed Behavior

The first planet vanishes for one frame, when hit very late, both vanish for the entire attempt.

Some tiles appear for one frame.

### Reproduction Rate

100% 

### Anything else?

https://user-images.githubusercontent.com/56203839/181778114-ee619087-65b3-4fb6-8afb-845b9b819b5a.mp4
[Player.log](https://github.com/7thbeatgames/adofai/files/9220626/Player.log)

**Comment by CrackThrough** [comment]
This happens because the camera event only runs at a precise beat. And the player cannot ensure their input is 100% frame-perfect. I replaced them with conditional events, so it should work as "intended" now.

**Comment by CrackThrough** [comment]
Actually, I realized I have to change all the other events such as moving decorations, but then they would be very out of sync with continuous decoration events. I don't think there is a feasible fix for this.

**Comment by CrackThrough** [comment]
Just had a shower thought I could probably add a planet following decoration

**Comment by authop** [comment]
This has been addressed (afaik)!
