### ISSUE TITLE
Add a tutorial for MO-X that teaches emote twirls for U-turns

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#31]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

MO-X uses twirl emotes on all U-turns and only some of them have twirls. At a first glance it seems like it's completely impossible to tell which U-turns have twirls, but they're actually tied to the direction the emote is pointing to. Most players won't know this so I think tutorialising is needed if it's going to stay this way

### Suggestion / Solution

Add a tutorial for MO-X that teaches emote twirls for U-turns

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
