### ISSUE TITLE
Make MO-X start on double speed and remove the hidden speed change on the first tile

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#32]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

The hidden speed change can be confusing

### Suggestion / Solution

Make MO-X start on double speed and remove the hidden speed change on the first tile

**Comment by authop** [comment]
This was to give more lenient judgments and countdowns. Starting with 290 BPM gives strictly narrower timing. It is also worth noting that as this is the start of the level, players can easily restart without worrying about their progress.

**Comment by Econtilde** [comment]
You're only making the first tile's timings more lenient by doing this and I don't think having an incorrect countdown (that can often lead to one or more deaths if you don't react fast enough) is justification for that
