### ISSUE TITLE
Add a "Sticky Camera" setting in the editor to the Misc Settings

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#33]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

I'm suggesting this because it's a previosuly existing feature that didn't pass the dev build since it would be incompatible with older levels but it would make the camera follow the player during moving tiles, which is useful for elevators or for things like making the camera follow the player when moving a pause tile

Feature in question: https://cdn.discordapp.com/attachments/852975084816695336/886668688135164004/adofai_elevator_cam.mp4

### Suggestion / Solution

Add a "Sticky Camera" setting in the editor to the Misc Settings

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
