### ISSUE TITLE
Add Shift-Esc to the Ctrl-H menu in the editor

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#34]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Shift-Esc, which exits play mode on the last tile you've touched, isn't in the editor's help menu

### Suggestion / Solution

Add Shift-Esc to the Ctrl-H menu in the editor

**Comment by Satellite-7th-Beat-Games** [comment]
Done in dev, thanks for reporting the issue! Special thanks to Antonio for huge improvements to the level editor shortcuts help menu.
