### ISSUE TITLE
Setting to remove the angle circle in the editor

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#35]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

If you already know all keybinds you don't need to see the angle circle and all it does is get in the way at times when trying to select tiles that are under one of the keys

### Suggestion / Solution

Setting to remove the angle circle in the editor

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
