### ISSUE TITLE
Add presets inside rabbit/snail events for x2 speed, x4 speed, x0.5 speed and x0.25 speed

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#36]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

It'd make charting a tiny bit faster since you can just tap a button to select the speed multiplier. The listed speed changes are the most common ones and the ones that are actually readable and don't need any additional indication

### Suggestion / Solution

Add presets inside rabbit/snail events for x2 speed, x4 speed, x0.5 speed and x0.25 speed

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
