### ISSUE TITLE
Add a toggle for mobile that turns on PC timing windows

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#38]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Mobile is more lenient than PC, which is fine in most cases but it makes it so speedruns on mobile are way more lenient than they are on PC. It'd be nice to have a toggle so timings can be standardized among all platforms

### Suggestion / Solution

Add a toggle for mobile that turns on PC timing windows, possibly alongside a indicator when playing that shows you're on PC timings

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
