### ISSUE TITLE
Change Otto's color relative to the current timing window cap

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#39]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Otto turns red at 300BPM despite Strict timings kicking in at 310BPM, which feels weird, and if there's an indicator for Strict timings through Otto, it'd be nice to have Otto be green up until 220BPM too so timing windows are linked to Otto

### Suggestion / Solution

Change Otto's color relative to the current timing window cap, green up to 220BPM, white up to 310BPM, red after 310BPM

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
