### ISSUE TITLE
Can't play my own workshop level

### ISSUE THREAD

**Issue by KabanFriends** [7thbeatgames/adofai#4]
### Is there an existing issue for this?

- [x] I searched for the issues, and made sure there were no duplicates.

### Contact Information

KabanFriends#7721

### Summary

I can't play the Steam Workshop level that I uploaded. The game gets stuck after entering the level, and before the starting countdown starts.
Workshop level: https://steamcommunity.com/sharedfiles/filedetails/?id=2839391821

![image](https://user-images.githubusercontent.com/45000995/181916263-fba7cf6e-cd59-47b1-b13a-5f1d99e1d85e.png)

### Version

v2.0.5 (r94)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Download [this Steam Workshop level](https://steamcommunity.com/sharedfiles/filedetails/?id=2839391821)
2. Enter the level from Custom Levels menu
3. Try to play the level

### Expected Behavior

Level countdown starts and the gameplay works

### Observed Behavior

The game gets stuck before the countdown

### Reproduction Rate

100%

### Anything else?

Log:
[Player.log](https://github.com/7thbeatgames/adofai/files/9226537/Player.log)

**Comment by CrackThrough** [comment]
Hi! I don't know if this is a mod issue, but this does not happen for me. Could you check if this issue still persists for you?

@KabanFriends

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
