### ISSUE TITLE
Add buttons that can increase or decrease specific numbers in the editor by 1

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#40]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Sometimes you want to copy an event and change the affected tile by one and you have to click the input field, delete the number and input the new one. For cases like these, it'd be nice to add buttons that can make certain number fields higher or lower by one

### Suggestion / Solution

Add buttons that can increase or decrease specific numbers in the editor by 1

### Demo & Mockup

https://cdn.discordapp.com/attachments/581668593993908234/844236688691429376/concepteditor.png

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
