### ISSUE TITLE
Background videos / BGA not working

### ISSUE THREAD

**Issue by WillTRM** [7thbeatgames/adofai#41]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Discord: WillTRM#7598

### Summary

Background videos do not play, there is just a black screen

### Version

v2.0.3 (r92)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. Play chart with background video

### Expected Behavior

Expected behavior: Video plays in background as intended

### Observed Behavior

Actual behavior: Black screen in background instead of video

### Reproduction Rate

100%

**Comment by authop** [comment]
Did you try to insert the video in the editor? Video is not happy with syncing/scrubbing compared with ogg audio. I will discuss this with the team but please don’t expect this too much.
