### ISSUE TITLE
Semi-Soft Lock in the Featured Level Screen

### ISSUE THREAD

**Issue by wolfplay013** [7thbeatgames/adofai#42]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

WolfPlay013#8948

### Summary

When you enter a level folder the blue gem appears normally. But if you change the sort settings or you exit out of the level the blue gem dissapears and gets replaced by chains.
![image](https://user-images.githubusercontent.com/60063537/182936461-cb4aaf41-d30c-46eb-ae31-1eb57ec75988.png)

### Version

v2.0.5 (r94) Alpha

### Operating System (OS)

Windows 10 21H2

### Platform

Steam

### Steps to Reproduce

1. Go to Featured Levels
2. Go to a level folder like Skyscape / Feral
3. Enter the level and quit it or change the sort settings.
4. Observe

### Expected Behavior

A blue gem is supposed to appear at the top that will get you out of the folder.

### Observed Behavior

It gets replaced by a chain.

### Reproduction Rate

100%

**Comment by wjdgustn** [comment]
it seems fixed now
