### ISSUE TITLE
exiting practice mode on a speed trial level will return you to the standard level, instead of the speed trial

### ISSUE THREAD

**Issue by wilrnilr** [7thbeatgames/adofai#43]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

wilr#9950

### Summary

if you enter a speed trial, start practice mode, and then exit practice mode, you'll be back on the standard level instead! checkpoints are usable, and it's played at 1.0x speed as usual - this seems to apply to all speed trials, both in the main game and custom levels

### Version

v2.0.5 (r94)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. enter a level's speed trial
2. enter practice mode
3. exit practice mode

### Expected Behavior

practice mode ends, and you're back on the speed trial (preferably at the speed you were playing at before entering practice mode)

### Observed Behavior

the standard level starts instead, and you have to re-enter from the menu to get to the speed trial

### Reproduction Rate

100%

**Comment by authop** [comment]
Thanks for the report! It has been fixed on the dev build.
