### ISSUE TITLE
Alt-dragging a tile should set the newly created position tile event to affect just the one tile

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#45]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Right now, when you alt-drag to reposition a single tile, it'll create 2 events - one to position the dragged tile, and a second to move the rest of the tiles back, cancelling them out. But in alpha, there's a new option under Position Track that allows you to move just the one track that's being positioned, which is preferable to creating 2 position events

### Suggestion / Solution

Alt-dragging tiles to reposition one at a time should enable Only change this tile, instead of creating 2 events that cancel out. This will make it a little smoother to work with, cause you can easily disable it if you wanted to reposition the entire track after the tile, rather than digging through events to delete the second Position Track event

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
