### ISSUE TITLE
Tile Resolution in level settings

### ISSUE THREAD

**Issue by wolfplay013** [7thbeatgames/adofai#47]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

When I would use the tile resolution event i cannot modify the first tile without using any third party tool like using surgery to put it on the 0th tile.

### Suggestion / Solution

Just put the Width and the Length settings in the Track Settings.

### Alternatives & Workarounds

Like I said using surgery to put it on the 0th tile.

### Demo & Mockup

![image](https://user-images.githubusercontent.com/60063537/184020325-59e88c01-a537-4cbb-8119-c1ef8a12755c.png)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
