### ISSUE TITLE
Add ability to enable/disable sticky tiles in the middle of a level

### ISSUE THREAD

**Issue by PizzaLovers007** [7thbeatgames/adofai#48]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Carryover popular request from the old tracking board.

### Suggestion / Solution

Have a new event that can turn on/off sticky tiles (with angle offset as well). Couple of cases to think about:

* Planets are off the tile and sticky tiles become enabled
* Player input early/late on tile that sticky tiles become disabled (planets might be in odd positioning)

**Comment by wjdgustn** [comment]
Added sticky tiles setting in PositionTrack event.
