### ISSUE TITLE
(r94 Alpha) Video backgrounds play during pauses instead of pausing the video.

### ISSUE THREAD

**Issue by wolfplay013** [7thbeatgames/adofai#5]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

WolfPlay013#8948

### Summary

I don't really have anything else to say other than what i said in the title.

> Video backgrounds play during pauses instead of pausing the video.

### Version

v2.0.5 (r94) Alpha

### Operating System (OS)

Windows 10 21H1

### Platform

Steam

### Steps to Reproduce

1. Go to a level that has a video background.
2. Pause for some time, the more time you wait the more it is noticeable.
3. Un-pause
4. Observe

### Expected Behavior

The background would pause until you would unpause.

### Observed Behavior

The background has played the entire time you have paused / waited.

### Reproduction Rate

100%

### Anything else?

This bug has actually existed for some time.

**Comment by CrackThrough** [comment]
Fixed the issue! The fix for this issue will be released in r99.
