### ISSUE TITLE
the neo cosmos hub and all of its levels appear bright pink, like a missing unity texture

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#52]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

wilr#9950

### Summary

entering the neo cosmos hub by either using ctrl-shift-N or the portal works fine, but you can't see anything

### Version

v2.0.5 (r94)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. enter neo cosmos, via the portal or the keyboard shortcut, or enter a level within the neo cosmos hub

### Expected Behavior

the hub or level is visible

### Observed Behavior

the hub or level instead appears bright pink, but the Exit text in the hub is visible - you can still navigate with number keys

### Reproduction Rate

100%

### Anything else?

screeenshots,,,
![image](https://user-images.githubusercontent.com/61643906/184756418-d3818751-00ec-4d2b-9dee-fd97dcef21c8.png)
![image](https://user-images.githubusercontent.com/61643906/184756425-40d7875c-4d6b-44f1-bd71-5be514273a12.png)

**Comment by actlists** [comment]
Same's happening to me
