### ISSUE TITLE
Text between the Artist and Song

### ISSUE THREAD

**Issue by XtraXD** [7thbeatgames/adofai#56]
### Please Check

- [x] I searched for the issues, and made sure there were no duplicates.
- [x] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Some people may want to change the hyphen (`-`) between the `Artist` and `Song` texts, for a diamond, a plus, a cross, `<->`, `XE-X`, or something else, without adding it to the `Artist` or `Song` fields. So, the text at the top of the screen is like `HyuN † Triple Cross`, but also, in the CLS, the artist text is `HyuN` and the song text, `Triple Cross` instead of `† Triple Cross`.

### Suggestion / Solution

A field for the text between Artist and Song ones, defaulted to ` - `.

### Demo & Mockup

Here's a representation made in Paint:
![suggestion](https://user-images.githubusercontent.com/46233874/187041976-f38734ff-e3b7-40cc-b4b5-9a063b682b24.png)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
