### ISSUE TITLE
Whenever I go into the level editor it freezes to a weird screen

### ISSUE THREAD

**Issue by Treble1196** [7thbeatgames/adofai#57]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

Discord: Treble#7777

### Summary

Steam added new code to the game, having it update, which also resulted in a weird bug--whenever I go into the level editor it freezes to a weird screen, and when you get to that screen you can't do anything--not even pause.
![20220829005708_1](https://user-images.githubusercontent.com/112370428/187127689-165c668f-7889-45ca-a6f7-564655cf8634.jpg)

### Version

v2.0.6 (r95)

### Operating System (OS)

Windows 11

### Platform

Steam

### Device Info

PC (Acer Nitro N50-610)

### Steps to Reproduce

1. Enter the game.
2. Enter the level editor.
3. The bug happens.

### Expected Behavior

I expected to use the level editor normally--I was playing this morning and everything was fine, but the added code that updated my game produced this bug.

### Observed Behavior

I went into the level editor and it froze to the screen I took a screenshot of above.

### Reproduction Rate

100%

### Anything else?

That's everything.

**Comment by PizzaLovers007** [comment]
Reverted alpha back to the previous version. Also, be sure to disable mods next time since those can cause issues when we release new updates.
