### ISSUE TITLE
New Input System Causing Input Problems With Controllers

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#58]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

notRat has me on his list again#4404

### Summary

When using a controller, all buttons used to work and it was similar if not identical to keyboard/mouse input. After a recent update, controller input has gotten a lot worse, with some buttons refusing to work and a lot of dropped inputs.

### Version

r95

### Operating System (OS)

Windows 10, Steam Deck

### Platform

Steam

### Device Info

Steam Deck, but issue is also present on Windows machines.

### Steps to Reproduce

This behavior is present at all times when using a controller, XInput or SteamInput do not assist (unless you use steaminput to force keyboard input but that's kinda missing the point), DInput controllers refuse to work entirely but always have so that's not changed.

### Expected Behavior

Controller input should be identical to keyboard input and not drop inputs frequently or ignore certian buttons.

### Observed Behavior

Controller input drops inputs frequently and ignores some buttons entirely, such as bumpers.

### Reproduction Rate

100%

**Comment by CrackThrough** [comment]
Fixed by giacomo!
