### ISSUE TITLE
holds on turnaround tiles will show an extra loop, if there's a twirl on the same tile

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#6]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

wilr#9950

### Summary

if you combine both a twirl and a hold on a turnaround tile, the hold will look like it has another loop on it, but it doesn't last any longer than it should (2 beats, for a hold with 0 extra loops)

### Version

v2.0.5 (r94)

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

Desktop

### Steps to Reproduce

1. shift+space to create a turnaround tile, and reposition the tile after it
2. add a hold to the turnaround tile
3. add a twirl to the turnaround tile

### Expected Behavior

the orbit should go the other direction, there should be no extra loops, and the color on the hold arc should line up with the planet's movement

### Observed Behavior

the hold shows 1 extra loop between the start and end, but gameplay remains the same, however many extra loops are chosen, and the coloring on the hold arc moves faster than your planet does

### Reproduction Rate

100%

### Anything else?

here's a video !!:

https://user-images.githubusercontent.com/61643906/182266472-b518dfbf-76bb-4061-986c-00c939e417db.mp4

**Comment by bugbard-cryptid** [comment]
~~i can't seem to reproduce this anymore as of v2.1.1 r98, so i'll close the issue !~~
well, it seems to still occur, but _only_ if there's also a multi planet event on the hold-twirl-turnaround tile :?

https://user-images.githubusercontent.com/61643906/199936001-ed6d75c8-e741-46c4-b121-5137b6fa38a4.mp4

**Comment by CrackThrough** [comment]
Not reproducible anymore, seems like this bug is fixed.

**Comment by bugbard-cryptid** [comment]
> Not reproducible anymore, seems like this bug is fixed. Does this issue still persist for you?

sorry for the wait ;; it doesnt seem like the bug is reproducible for me either ::]

**Comment by bugbard-cryptid** [comment]
*i forgot about the 3planet part of the bug ahhgfgh - while it's no longer reproducible with hold+twirl on a turnaround, like the video above shows, it's still possible with hold+twirl+3planet, so i'll reopen the issue
![image](https://github.com/7thbeatgames/adofai/assets/61643906/aba9d5f2-9e3d-4113-b646-5a8faf07bd4e)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these symptoms, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
