### ISSUE TITLE
Speed Trials "High Score" Starts at 0.0x and not 1.0x like it used to

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#60]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

notRat has me on his list again#4404

### Summary

When you unlock a stage's speed trials, it used to start the "high score" at 1.0x, but recently that has changed to be 0.0x, and is only updated if you beat the stage at any speed, including 1.0x or lesser.

### Version

r94, r92

### Operating System (OS)

Windows 10

### Platform

Steam, Itch

### Steps to Reproduce

1. Beat a stage for the first time and unlock it's speed trial variant.

### Expected Behavior

Speed trial "High Score" starts at 1.0x

### Observed Behavior

Speed trial "High Score" starts at 0.0x

**Comment by Patashu** [comment]
IMO it *should* say 0.0x until you have beaten it at any speed without checkpoints used. 1.0x with checkpoints is completely different from 1.0x without checkpoints (e.g. in a speed trial or just by not dying).

**Comment by wolfplay013** [comment]
do you mean that it should say 0.0x when you die with checkpoints

**Comment by Patashu** [comment]
It should say 0.0x until you have beaten the Speed Trial at any speed (then it'll say that speed) or beaten it normally with no checkpoints (then it'll say 1.0x). Then you don't have to distinguish between '1.0x' and '1.0x (without checkpoints)'. They'll be '0.0x' and '1.0x' respectively.

**Comment by wolfplay013** [comment]
ohhh now i get it
