### ISSUE TITLE
Practice Mode Lets You Clear Checkpoints

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#61]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

notRat has me on his list again#4404

### Summary

Report from Steam Community:
https://clips.twitch.tv/HardBenevolentLettucePupper--DMVokrw8OZvmTQt
Wherein a player gets through a XO-X section on practice mode and gets to another checkpoint, whereupon leaving practice mode they are placed back on that checkpoint.

### Version

r94

### Operating System (OS)

Windows

### Platform

Steam

### Steps to Reproduce

Practice a section in XO-X until you reach a checkpoint.

### Expected Behavior

Practice mode takes you back to the start/last actually completed checkpoint.

### Observed Behavior

Practice mode resumes you at the new checkpoint.

**Comment by authop** [comment]
Thanks for the report! It has been fixed on the dev build.

**Comment by notdonte** [comment]
This issue doesn't seem to be reoccuring on current beta.
