### ISSUE TITLE
ADOFAI refuses to stop running when closing from Steam

### ISSUE THREAD

**Issue by actlists** [7thbeatgames/adofai#64]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

polyrhythm#0001

### Summary

Whenever trying to close the Steam version of the game, it gets stuck on "Stopping". I have to close Steam entirely to re-open the game, as it says you can't open it because it is still running. It doesn't seem to be on Task Manager, either.

### Version

r95 Windows

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. Open the game
2. Close the game

### Expected Behavior

I expect the game to just close, instead of just getting stuck.

### Observed Behavior

Every time I would try to close the game, it gets stuck on "Stopping" on Steam, and there is no way to open it. I checked Task Manager, Restarted Steam, Reinstalled the game, to no avail.

### Reproduction Rate

100% - Started happening a week ago.

**Comment by authop** [comment]
What's your method to close out the game?
- Exit button on the pause menu
- Alt-F4
- Task manager
- via Steam interface

If you resolved this issue by trying other closing methods, what option makes the game freeze?

**Comment by actlists** [comment]
I use the Steam interface to close it

**Comment by authop** [comment]
I'm closing this issue as I can't find a way to reproduce this. 
To future readers: Any help is appreciated. Please let us know via comment when you figure out how to reproduce this.
