### ISSUE TITLE
T2-EX music doesn't play

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/adofai#65]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

In the level T2-EX sing sing red indigo, the music does not play. Hitsounds continue to play normally.

### Version

v2.0.6 (r95) Mac

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Steps to Reproduce

1. Enter level T2-EX
2. See error

### Expected Behavior

The level music would play.

### Observed Behavior

The level music doesn't play.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/adofai/files/9485953/Player.log)

**Comment by authop** [comment]
The new build has moved to the default. Please update the game and try again to see if the problem persists.

**Comment by Non-Binary-Programmer** [comment]
It appears to be fixed. Thanks!
