### ISSUE TITLE
the camera flies very far away from the track in Options

### ISSUE THREAD

**Issue by wilrnilr** [7thbeatgames/adofai#66]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

during a later segment of options (shortly after the drunken python), when the camera should zoom out and move slightly, it will instead move far enough upward that the track is no longer visible

### Version

v2.0.6 (r95)

### Operating System (OS)

Linux (KDE neon 5.25)

### Platform

Steam

### Steps to Reproduce

1. play Options

### Expected Behavior

the camera moves only slightly, leaving the track still visible to the player

### Observed Behavior

camera moves too far, and the track is no longer visible

### Reproduction Rate

100%

### Anything else?

viiideo !

https://user-images.githubusercontent.com/61643906/189762015-3719d30e-9ead-45f5-a550-630faa9f7bf2.mp4

**Comment by wilrnilr** [comment]
an update: it no longer seems to be happening to me? it happened twice in a row, but after starting from the checkpoint where the camera misbehaves,,, no more weird camera! even after restarting the whole level or restarting the game... huh;

**Comment by authop** [comment]
Noted! As there is no clear way to reproduce this, I'll close this issue for now.

**Comment by actlists** [comment]
> Noted! As there is no clear way to reproduce this, I'll close this issue for now.

This is happening to me as well, also in custom levels

**Comment by authop** [comment]
I asked the team and found this was related to async. Giacomo fixed this!
