### ISSUE TITLE
창작마당 메타데이터 파일 분리

### ISSUE THREAD

**Issue by wjdgustn** [7thbeatgames/adofai#67]
### 문제점

창작마당에서 레벨 리스트를 불러올 때 메타데이터를 읽기 위해 전체 레벨 json을 파싱하기 때문에 로딩 속도가 느립니다

### 제안 및 해결 방법

창작마당에 게시할 때 리스트 표시에 필요한 메타데이터 json은 별도의 파일로 분리해주세요.
이미 업로드된 레벨은 처음에 한해 레벨 파일을 읽어 메타데이터 파일을 생성하도록 해주세요.

### 대체 방안

비공식 모드를 이용해 레벨 파일에서 actions와 pathData, angleData를 제거해본 결과, 약 5배(20.11621초 --> 4.089355초)로 속도가 향상되었습니다.

해당 모드의 소스코드 : https://github.com/wjdgustn/FixCLS/blob/master/FixCLS/MainPatch.cs#L82-L112

**Comment by authop** [comment]
<h2>Translation: Separate metadata from the Workshop levels to boost load speed</h2>
<h3>Problem</h3>
The game reads all of the level files to obtain metadata, and that makes load speed slower.
<h3>Solution</h3>
Separate metadata JSON to somewhere else. For existing levels, make metadata JSON to another file/path automatically.
I can confirm the load speed went 20 seconds to 4 seconds when I erased all of the actions, pathData, and angleData from the level file by using a mod.

**Comment by authop** [comment]
테스트를 위해 불러왔던 레벨은 총 몇 개였나요?

**Comment by wjdgustn** [comment]
약 400개였습니다
