### ISSUE TITLE
overlapping inputs may be dropped, when asynchronous input system is enabled

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#69]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

on the async input system, when button presses overlap (usually during high-speed segments where more than 1 key is a necessity) inputs are often dropped
rarely (??) extra inputs will appear instead? i cannot figure out how to replicate it

### Version

v2.1.0 (r97) Linux

### Operating System (OS)

Linux (KDE neon 5.25)

### Platform

Steam

### Steps to Reproduce

1. play the game with more than 1 key (usually this will happen naturally at faster bpms)

### Expected Behavior

inputs behave as you'd expect, no extra or fewer inputs

### Observed Behavior

overlapping inputs may either be dropped or rarely cause an extra, early press, which can lead to a miss or an overload

### Reproduction Rate

100% (input drops - i cant replicate extra presses yet)

### Anything else?

some videos,,, 
playing OFN with 2 keys, releasing a key right as i press the other one (i'm not missing any key presses in this video! they just get dropped)

https://user-images.githubusercontent.com/61643906/192652262-77a6b179-c1cb-4590-b36a-75509d0b524e.mp4

a previous video of me playing OFN with async inputs enabled, immediately releasing all my keypresses to avoid overlap, and then allowing overlap as usual - this time it caused extra presses to appear, but i'm not sure why!

https://user-images.githubusercontent.com/61643906/192652614-3084e2aa-24dd-41f7-adc6-46dd4bb18d9f.mp4

**Comment by wilrnilr** [comment]
* it seems that extra inputs consistently appear on overlapping button presses when you're using the _standard_ input system - i'll make a separate issue for that!!

**Comment by bugbard-cryptid** [comment]
neither of the bugs about overlapping inputs causing dropped/extra inputs seem to be happening to me anymore,,, so i'll close both of the issues for now, unless someone is still experiencing them !
