### ISSUE TITLE
pause tiles may last 1 beat longer than expected, if they're placed on a straight tile between non-cardinal bends

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#7]
### Is there an existing issue for this?

- [X] I searched for the issues, and made sure there were no duplicates.

### Contact Information

wilr#9950

### Summary

in some situations, if a pause tile is put on a non-cardinal direction (like between two bends) it can last longer than it should, it seems to just be 1 extra beat every time?

### Version

v2.0.5 (r94)

### Operating System (OS)

Windows 10

### Platform

Steam

### Steps to Reproduce

1. create a continuous swung offbeat, so that there is a straight tile between two bends (one outer bend, one inner bend - like the ones you'd see in the midnight train)
![image](https://user-images.githubusercontent.com/61643906/182273937-7d292066-97b5-4eb4-9c01-1ec320cb1d25.png)

2. on the straight tile between the bends, add a pause, and set its duration to 0 (any other duration will work, but it's clearest on 0)

### Expected Behavior

the pause tile should last for 0 beats, not affecting the gameplay

### Observed Behavior

the pause tile will instead last for 1 beat

### Reproduction Rate

~100% (i don't know *what* causes it, but i can sort of replicate it)

### Anything else?

here's an example level full of 0-beat pauses showing the bug (tiles colored pink are where pauses last an extra beat instead of 0), a video of it occurring in the level, and a video of it occurring in bloo cat bloo on a 1-beat pause, where i first noticed the bug:

[pausebug.zip](https://github.com/7thbeatgames/adofai/files/9238419/pausebug.zip)

https://user-images.githubusercontent.com/61643906/182274502-cb17d095-43e3-4729-9183-acda0b38b9a6.mp4

https://user-images.githubusercontent.com/61643906/182273028-4a3bd35a-691d-4dc3-ab5e-7df934d38a62.mp4

**Comment by CrackThrough** [comment]
Hi, Sorry about the very late response. But I think this should be fixed for now, or at least most of the time.

I tried to fix the turnaround tiles (360˚ tiles) not pausing for an extra beat. I still know that formula for deciding whether it is a turnaround tile is wrong so we have false positives like this. It will take a long time, but I'll still try to fix it.

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
