### ISSUE TITLE
overlapping inputs on the standard input system will frequently cause extra inputs to register

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#70]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

on the standard input system (non-asynchronous), overlapping button presses tend to cause enough extra inputs to appear that you'll overload

### Version

v2.1.0 (r97) Linux

### Operating System (OS)

Linux (KDE neon 5.25)

### Platform

Steam

### Steps to Reproduce

1. play the game with more than 1 key (this happens naturally at higher speeds, on OFN or Options, for example)

### Expected Behavior

input behaves as usual - no extra button presses

### Observed Behavior

extra button presses are detected when inputs overlap, frequently causing overload

### Reproduction Rate

100%

### Anything else?

videos ! i'm playing the game as i'd normally play with 2 keys,,, pressing one of them and releasing the other at the same time
one forgotten night

https://user-images.githubusercontent.com/61643906/192653890-d28c0e55-3e77-41fb-96e1-f3c272f35c97.mp4

options

https://user-images.githubusercontent.com/61643906/192653899-f09d03cd-aeb7-4ae7-8bb9-519efaea0872.mp4

**Comment by CrackThrough** [comment]
@bugbard-cryptid Is this reproducible in r98?

**Comment by bugbard-cryptid** [comment]
not anymore, it seems! i'll close the issue, if that's ok
