### ISSUE TITLE
On Asynchronus Input System RJ-X's doubletap beats cannot be hit without overloading

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#71]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

notRat has me on his list again#4404

### Summary

From steam community:
When playing with the new input system, RJ-X causes overloads commonly due to it's doubletap beats.

### Version

r97

### Operating System (OS)

Windows 7, confirmed on other Windows machines

### Platform

Steam

### Steps to Reproduce

1. Enable new input system in settings.
2. Play RJ-X
3. During doubletap beats notice multiple miss notifications

### Expected Behavior

Doubletap beats work as intended

### Observed Behavior

Doubletap beats are played but add a lot of misses and eventually cause an overload.

### Reproduction Rate

100%

**Comment by Non-Binary-Programmer** [comment]
Does not occur on Mac r98; either error is Windows exclusive or is fixed in r98

**Comment by Gotchfutchian** [comment]
This bug does not occur at all on Linux r98. Although, if in the same session you enables async input, the main menu always selects the option hovered over when using keyboard inputs.

**Comment by CrackThrough** [comment]
I could not reproduce. I think this is something to do with a mistake I introduced in r97 while implementing Asynchronous Input System.

@notdonte Could you see if the issue persists at r98, since I fixed the said feature in r98?

**Comment by notdonte** [comment]
> 

Apologies for the wait, I have confirmed on my end the issue doesn't occur anymore on live or beta, closing issue.
