### ISSUE TITLE
Using + and - to play causes the camera to freeze during hold notes

### ISSUE THREAD

**Issue by Aaeeschylus** [7thbeatgames/adofai#73]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

aaeeschylus#6645

### Summary

Whenever you use + and - to play, the camera will freeze in place during hold notes, making it impossible to see the end of the hold note in some cases.

### Version

v2.1.0 (r97) Windows

### Operating System (OS)

Windows 11

### Platform

Steam

### Steps to Reproduce

1. Play a song with hold notes (ie. World T1)
2. Use + and - to play the start past the first set of hold notes (including the long one)

### Expected Behavior

The camera follows the hold note

### Observed Behavior

The camera freezes in place

### Reproduction Rate

100%

### Anything else?

I posted a video in the discord since it is too big for github. Here is the message link: https://discord.com/channels/959280727671836682/959284450297016410/1033734989046616104

Otherwise, contact me through Discord DM and I can send it there too.

**Comment by authop** [comment]
Those keys are reserved for camera debug purposes. We’ll consider this to turn this on only for debug mode.

**Comment by Aaeeschylus** [comment]
that would be amazing if you could (or at least a toggle of some sort). I can't rebind the board I use for rhythm games and + and - are what the main two keys are set to.

**Comment by wjdgustn** [comment]
this seems removed
