### ISSUE TITLE
changing volume in the level editor only takes effect after exiting to the main menu

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#75]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

if you change the game volume from the settings menu in the editor, it'll only take effect after you leave the level editor
this _only_ applies to volume, it seems!

### Version

v2.1.1 (r98) Linux

### Operating System (OS)

Linux (KDE neon 5.26)

### Platform

Steam

### Steps to Reproduce

1. enter the level editor
2. in the dropdown menu at the top of the screen, go to settings and change volume

### Expected Behavior

volume changes immediately take effect

### Observed Behavior

volume changes only take effect when i leave the level editor

### Reproduction Rate

100%

### Anything else?

waawa video

https://user-images.githubusercontent.com/61643906/197884955-11cf36da-bc64-4b9a-a075-6692d3282c0c.mp4

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
