### ISSUE TITLE
using set orbit easing + 3 planets looks a bit unusual

### ISSUE THREAD

**Issue by bugbard-cryptid** [7thbeatgames/adofai#76]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

wilr#9950

### Summary

if you change the planet orbit ease to something other than linear, planets appear to snap toward each other at the start of the ease

### Version

v2.1.1 (r98) Linux

### Operating System (OS)

Linux (KDE neon 5.26)

### Platform

Steam

### Steps to Reproduce

1. in the level editor, place a set orbit easing event, or change it via the side panel to something other than linear
2. place a set planet count event

### Expected Behavior

planets ease as you would expect, staying evenly spaced from each other

### Observed Behavior

the orbiting 2 planets appear to snap next to each other, before drifting apart

### Reproduction Rate

100%

### Anything else?

a video ,,

https://user-images.githubusercontent.com/61643906/198422290-ba181bb4-8c22-46b9-b6c9-1ac918565800.mp4

**Comment by TaroNuke** [comment]
https://user-images.githubusercontent.com/633391/204387249-54daa17b-03c9-436b-977a-4077f5269dc9.mp4

fixed
