### ISSUE TITLE
Escape Menu Not Working

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/adofai#77]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223 (won't accept DMs)

### Summary

Pressing escape triggers a regular input instead of returning to the menu. I believe this is based on asynchronous input, which I had enabled when I updated to the newest version, but I can't open the menu to test.

### Version

Latest alpha (can't open menu to check)

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Device Info

MacBook Pro (14-inch, 2021) with M1 chip

### Steps to Reproduce

1. Launch game on latest alpha
2. (maybe) have async input enabled
3. Press Escape

### Expected Behavior

The menu would open.

### Observed Behavior

The game would behave as if a regular input occurred, and move the planets one step without opening the menu.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/adofai/files/9889172/Player.log)

**Comment by bugbard-cryptid** [comment]
i remember at some point my arrow keys on the pause menu suddenly behaved like regular inputs, but it went away after i relaunched adofai, and i wasn't sure how to reproduce it ,,, maybe this is related too :?

**Comment by authop** [comment]
Forwarding this to issue #69
