### ISSUE TITLE
레벨 에디터 내 일본어 오역

### ISSUE THREAD

**Issue by ppapman1** [7thbeatgames/adofai#78]
### 요약

레벨 에디터에서, 왼쪽 패널의 레벨 설정 탭에서 맨 밑에서 세 번째 항목(Artist Links)의 라벨이 アーテイストリンクのリンク로 돼 있습니다.
![20221101_002029](https://user-images.githubusercontent.com/48434316/199223944-cb542889-27a4-485e-abc1-f9d18b929f98.png)

### 재현 방법

1. 불과 얼음의 춤을 일본어로 설정합니다.
2. 레벨 에디터로 들어갑니다.
3. 왼쪽 패널에서 레벨 설정 탭을 들어갑니다.
4. 맨 밑에서 세 번째 항목을 봅니다.
5. 관경을 구경합니다.

### 예측 결과

라벨이 アーテイストリンク여야 합니다.

### 실제 결과

라벨이 アーテイストリンクのリンク입니다.

### 재현율

140%

### 버전 및 플랫폼

- 게임 플랫폼: 스팀
- 게임 버전: v2.1.1 (r98)

### 그 외

'アーテイストリンクのリンク'는 한국어로 대응시켜 보면 '아티스트 링크의 링크'라는 뜻입니다. 물론 한국에서도 일본에서도 이렇게 쓰는 사람은 없습니다.

문제를 해결하려면 한국어에서 '의 링크'에 해당하는 'のリンク' 부분을 삭제하면 됩니다. 즉, 'アーテイストリンク'이어야 합니다.

**Comment by authop** [comment]
해당 문제가 수정되었으며, 다음 번역문 업데이트 때 반영될 예정입니다.

**Comment by toswmxlql** [comment]
> 해당 문제가 수정되었으며, 다음 번역문 업데이트 때 반영될 예정입니다.

죄송합니다!! 이슈 원문에 오타가 있었습니다.

**오타**
アーテイストリンク

**정상**
アーティストリンク

(네 번째 글자에서 작은 ィ를 써야 하지만 큰 イ를 씀)

이슈에 있는 문자열로 그대로 수정하셨다면 アーティストリンク로 다시 한번 수정해 주시면 감사하겠습니다.

번거롭게 해 드려 죄송합니다!!

**Comment by ppapman1** [comment]
> 해당 문제가 수정되었으며, 다음 번역문 업데이트 때 반영될 예정입니다.

죄송합니다!! 이슈 원문에 오타가 있었습니다.

**오타**
アーテイストリンク

**정상**
アーティストリンク

(네 번째 글자에서 작은 ィ를 써야 하지만 큰 イ를 씀)

이슈에 있는 문자열로 그대로 수정하셨다면 アーティストリンク로 다시 한번 수정해 주시면 감사하겠습니다.

번거롭게 해 드려 죄송합니다!!

(아까 다른 계정으로 코멘트 올렸습니다. 알림이 두 개라면 하나는 무시해 주세요)
