### ISSUE TITLE
언어를 변경해도 레벨 에디터에서 인풋 필드 Placeholder가 변경되지 않음

### ISSUE THREAD

**Issue by ppapman1** [7thbeatgames/adofai#79]
### 요약

언어를 변경해도 레벨 에디테에서의 인풋 필드의 플레이스홀더(Placeholder)가 변경되지 않습니다.

### 재현 방법

1. 레벨 에디터로 들어갑니다.
2. 다른 언어로 변경합니다.
3. 문제 발생

### 예측 결과

다른 부분처럼 인풋 필드의 Placeholder도 번역이 적용돼야 합니다.

### 실제 결과

번역이 적용되지 않고 원래의 문자열이 그대로 남아 있습니다.

### 재현율

100%

### 버전 및 플랫폼

- 운영체제: Windows 11
- 게임 플랫폼: 스팀
- 게임 버전: v2.1.1 (r98)

### 그 외

![image](https://user-images.githubusercontent.com/48434316/199225367-1244332f-97f5-4c94-9140-b3bdde425fa2.png)

**Comment by authop** [comment]
## Placeholder not updated when changing language
Placeholders on the input field are not updated when changing the language to others.

### Steps
1. Go into the level editor
2. Change the language
3. Observe

### Expected
Placeholders in the input field should update with the target language

### Observed
Placeholder remain as-is

**Comment by wjdgustn** [comment]
it was fixed by paring!
