### ISSUE TITLE
Re-add the "Add Decoration" and "Add Text" events

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#8]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

The Decorations tab is a great concept and can be really useful in some instances, but it's missing some key features that make it a lot slower to manage in multiple cases when it would've been absolutely fine if we had the Add Decoration events. Talking from experience, I recently worked on an asset heavy level and if I had the old events I would've been able to finish it hours earlier than when I did.

### Suggestion / Solution

Re-add the "Add Decoration" and "Add Text" events, while still keeping the Decoration tab. This way the benefits of both systems are kept. Additionally, if they got re-added, make it so adding Decorations and Text in the Decorations tab gets tied to a tile if a tile number for the Decoration is chosen

**Comment by CrackThrough** [comment]
Hello, we're sorry for the very late response. I'm not sure if this is still a valid suggestion since people got used to the current system (whether they liked it or not, some may have quit because of this) and I'd love to hear your thoughts.

We added features to copy and paste, and select multiple decorations a few months ago because that was one of the most wanted features by level creators. Let me know if the decoration tab feature is still lacking something to this day.

**Comment by CrackThrough** [comment]
So if I understood this right:
- Decorations list should only display items relative to the selected tile's number
- Re-add event buttons to use as a shortcut (just like how twirl and speed change event works)
- No force changes, just an additional setting that allows this

Correct?

**Comment by Econtilde** [comment]
Sorry for the late response (regarding your 14 day old comment). The Decoration tab was and still is pretty solid, but in some specific instances it can be slower to work with it than it was to work with the Decoration events, since you could copy and paste them as if they were just another event, and depending on what you wanted to do, it could save hours of work. 

But regarding all this, I guess it's now sort of obsolete since I talked with Giacomo about this some time ago and we agreed on adding a decoration to the Decoration tab also adding it to the tabs on the right as it if were an event so you can copy and paste it around more easily. You should maybe talk about this with him since you two may be working on the same the same thing without knowing
