### ISSUE TITLE
Final Tile Requires Second Press to End Stage

### ISSUE THREAD

**Issue by VGmaster670** [7thbeatgames/adofai#80]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

Discord: VGmaster#3086

### Summary

The final tile must be hit twice in order to complete the level, as the planets will snap back to the previous tile and require to do another input, and if you fail the second hit, you will fail the level and it won't have been marked as completed.

### Version

v2.1.1 (r98)

### Operating System (OS)

Windows 10

### Platform

Steam

### Device Info

PC

### Steps to Reproduce

1. Load any level (including customs)
2. Play level until completion

### Expected Behavior

The level ends upon hitting the final tile.

### Observed Behavior

Planets snap back to the previous tile, requiring one more hit to complete the level, otherwise, the attempt will be failed and the level will not have been considered complete.

### Reproduction Rate

100%

### Anything else?

https://user-images.githubusercontent.com/72361126/200184906-d218243c-9ec5-4cfb-8412-897c6aeb2527.mp4
[Player.log](https://github.com/7thbeatgames/adofai/files/9946378/Player.log)

**Comment by authop** [comment]
I can see you are using mods. Please delete all mods and try again to see if the issue persists.

**Comment by VGmaster670** [comment]
Well it seems to be fixed when I checked to see if it still happened even with mods enabled today so I guess I'll close this issue
