### ISSUE TITLE
Xtra Worlds Achievement Not Triggering (Steam)

### ISSUE THREAD

**Issue by notdonte** [7thbeatgames/adofai#82]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

From steam community:
i already complete all xtra worlds, even the speed trials.
but i don't have de achievement, strange...

Can't confirm issue on my end but it's minor enough to forward here.

### Version

r98 (alpha)

### Operating System (OS)

Windows(?)

### Platform

Steam

### Steps to Reproduce

Beat all Xtra worlds.

### Expected Behavior

Gain Xtra Worlds Complete - Finish all worlds of the Xtra Island steam achievements.

### Observed Behavior

Achievement isn't given.

**Comment by authop** [comment]
Closing this issue, since there’s no similar report.
