### ISSUE TITLE
Last checkpoint in ML-X is hidden until activated

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#84]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Summary

Last checkpoint in ML-X is hidden until activated

### Version

v2.1.1 (r98)

### Operating System (OS)

Windows

### Platform

Steam

### Steps to Reproduce

Play ML-X normally

### Expected Behavior

Checkpoint tile icon should be visible

### Observed Behavior

It is not

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
