### ISSUE TITLE
[ADOFAI] 장식 탭에서의 폴더 기능

### ISSUE THREAD

**Issue by qaplzm0915** [7thbeatgames/adofai#86]
### 검색 먼저

먼저 [이슈](https://github.com/7thbeatgames/adofai/issues)를 검색하여 이미 다른 사람이 관련 이슈를 제출했는지 확인해보세요.

해당 이슈가 중복되었다면 관리자는 제출한 이슈를 종료 처리하게 됩니다. 중복된 이슈를 새로 만드는 대신, 다른 사람이 제출한 이슈에 👍 이모트를 달아주세요.

### 한국어 안내

비록 한국어를 지원 대상에 포함하고 있기는 하나, 개발자들은 영어를 표준으로 쓰고 있습니다. 때문에 개발자들은 대부분 기계 번역으로 한국어 이슈를 접하게 됩니다.

한국어로는 의사 소통이 다소 원활하지 않을 수 있는 점 양해를 부탁드리며, 기계 번역이 원활히 될 수 있도록 문법을 지키며 글을 작성해주시기 바랍니다.

### 자주 묻는 질문 확인

[자주 묻는 질문](https://7thbeat.notion.site/ADOFAI-8dc4ef47b27d465cb90c792a51ccb543) 페이지에 답변이 이미 있을 수도 있습니다.

### 약관

7th Beat Games는 지적 재산권 또는 기타 방식에 따른 의무, 로열티나 제한 없이 자사 제품 또는 서비스에 대한 피드백을 무제한적으로 사용, 복사, 공개, 라이선스 부여, 배포 및 활용할 수 있습니다.

7th Beat Games는 피드백의 수용 여부 관계 없이 제품 또는 서비스를 독립적으로 사용, 개발, 평가 또는 마케팅할 수 있는 권리를 보유합니다. 제안을 작성하는 것으로 이 약관에 동의하게 됩니다. 약관에 동의하지 않는다면 제안을 제출하지 마십시오.

이 줄을 포함한 상단의 모든 내용을 삭제한 후 이슈를 작성해주시기 바랍니다.

---

### 문제점

제안을 하게 만든 문제를 명확하게 설명해주세요.

### 제안 및 해결 방법

어떤 일이 일어나길 원하는지 명확하게 설명해주세요.

### 대체 방안

문제를 해결하기 위해 시도해봤던 대안적 방법이나 기능이 있나요?

### 데모 및 목업

제안하고자 하는 기능을 소개하는 이미지나 비디오를 첨부하세요.

### 그 외

제안과 관련된 기타 설명을 적어주세요.

장식탭에서의 폴더 기능을 추가해주세요.
몇십개의 장식이 일렬로 늘어져있는 리스트에서 무언가를 사용하는건 힘들고 불편합니다

**Comment by authop** [comment]
## Add the folder at the decoration tab

The decoration list that has a bunch of items (let’s say 20+) is incredibly hard to use.

**Comment by authop** [comment]
It is planned along with the editor redesign. I'm closing this issue for now.
