### ISSUE TITLE
Change the "Press Space to begin" text to "Press any key to begin"

### ISSUE THREAD

**Issue by Econtilde** [7thbeatgames/adofai#9]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

While small stuff like this that has stayed in the game for a long time makes the game more charming, this thing in specific can sometimes mislead players going in blind into the game into believing that they can only use the spacebar to play the game

### Suggestion / Solution

Change the "Press Space to begin" text to "Press any key to begin" as well as any other mentions of using Space to just "any key"

**Comment by authop** [comment]
It has been addressed. Please wait for a while, as it will be reflected along with other patches.
