### ISSUE TITLE
Play event tag on hitbox collision

### ISSUE THREAD

**Issue by prodzpod** [7thbeatgames/adofai#91]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Just like the "Set conditional events" event, being able to execute a custom set of events on collision is one of the most requested features among various communities, both English and Korean. This will allow for a (albeit limited) rdcode-like behavior, and I believe this feature would allow for great expansion in technical (as in levels that deviate greatly from the ordinary ADOFAI gameplay, through gimmicks or them being notADOFAI) levels.

### Suggestion / Solution

Since decorations arent tied to tiles anymore, the event tag could be found from the last tile or from all tiles, as if they're from one tile (by ignoring "floor"). One could also think of a seperate event tab where conditional events and the like could reference events from, but the development cost does not seem to be worth it.

### Alternatives & Workarounds

"set conditional events" comes closest, but the usage is limited.

### Demo & Mockup

if #92 is implemented with it:
![20221213193545_1](https://user-images.githubusercontent.com/38210271/207296636-46d737eb-6d94-460d-bdb0-febfb003b4aa.png)
if not:
![20221213193600_1](https://user-images.githubusercontent.com/38210271/207296488-95c171d3-1d8b-464c-b2e6-d1de6784c07a.png)

**Comment by wjdgustn** [comment]
done!
