### ISSUE TITLE
faster appearance of tile 199 on classy kitty

### ISSUE THREAD

**Issue by prodzpod** [7thbeatgames/adofai#94]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

[Classy Kitty](https://steamcommunity.com/sharedfiles/filedetails/?id=2488171556), one of the featured levels has a section where a non-repeating, non-straight tile appears 2 beats before. this also happens to be the hardest section of the level due to how hard it is to read (two twirls in a row makes the following square stack unintuitive). I believe that the gameplay could be vastly improved if the tiles appeared sooner.

### Suggestion / Solution

put the event on tile 191 to have the appear duration be 4 beats instead, or somewhere along there

### Demo & Mockup

[altered .adofai file](https://cdn.discordapp.com/attachments/515678821408571392/1052229371831783555/main_altered.adofai) (just the .adofai file, requires the actual level to work)

**Comment by authop** [comment]
Nichipe updated the level as per requested!
