### ISSUE TITLE
Android practice mode doesn't change speed correctly after death

### ISSUE THREAD

**Issue by MaxBareilles** [7thbeatgames/adofai#95]
https://user-images.githubusercontent.com/52111978/208264680-033a585e-2a99-473b-9ac0-3c08f1eecbac.mp4

When you die in practice mode, and then click the pause menu to change the speed, when you try to click the change speed button, instead it resets you to the start of the practice without changing speed.

Android 2.1.1 r98

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
