### ISSUE TITLE
XN-X Trans-Neptunian Object checkpoints broken

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/adofai#96]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223

### Summary

In the level XN-X, if the player dies after touching a checkpoint, the game will not prompt them to continue and they are stuck until they either restart or leave the lever. This also occurs when trying to continue from the main hub.

### Version

v2.3.0 (r100) Mac

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Device Info

MacBook Pro (14-inch, 2021) with M1 Pro chip

### Steps to Reproduce

1. Enter XN-X
2. Play normally until you reach a checkpoint
3. Die
5. Quit game
6. Relaunch game
7. Continue using portal on the left
8. See error

### Expected Behavior

The game would allow the user to continue from the checkpoint.

### Observed Behavior

The game does not allow them to continue from the checkpoint.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/adofai/files/10299059/Player.log)
<img width="1512" alt="Screen Shot 2022-12-24 at 1 02 09 PM" src="https://user-images.githubusercontent.com/100527514/209448631-1a93e026-ff46-450d-82be-c9e658bb2328.png">

**Comment by fizzd** [comment]
Thank you! We've fixed this on the next version now.
