### ISSUE TITLE
XN-X "Cosmic Honeycomb" pattern graphics don't load

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/adofai#97]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223

### Summary

In XN-X, the graphics for the pattern shown in the tutorial level XN-2 Cosmic Honeycomb do not load properly. However, the gameplay is not affected.

### Version

v2.3.0 (r100) Mac

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Device Info

MacBook Pro (14-inch, 2021) with M1 Pro chip

### Steps to Reproduce

1. Enter XN-X
2. Play through the level
3. See error after second checkpoint

### Expected Behavior

A graphical representation of the notes for the "Cosmic Honeycomb" pattern would appear.

### Observed Behavior

No tiles would appear.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/adofai/files/10299072/Player.log)
<img width="1512" alt="All the tiles are lit up, but the tiles for the 'Cosmic Honeycomb' pattern are not visible." src="https://user-images.githubusercontent.com/100527514/209448840-1671d9d5-55ec-4edb-845f-639af8ad7bed.png">

**Comment by Non-Binary-Programmer** [comment]
Upon reverting to the stable version, I discovered that there are supposed to be a lot more graphics in this level than appear in this version.

**Comment by fizzd** [comment]
Thank you so much, we've fixed this on the next version now.
