### ISSUE TITLE
"Lock Rotation" option for decoration

### ISSUE THREAD

**Issue by prodzpod** [7thbeatgames/adofai#98]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [X] I agree the terms, and understand that my suggestion is not guaranteed to be added or addressed.

### What problem motivated you to submit the suggestion?

Like backgrounds, ability to lock rotation of a decoration is one of the most recommended features. It's been recommended in 7BGC's #adofai-suggestions multiple times before, and this issue is to relay it to the tracker.

### Suggestion / Solution

Add a "lock rotation" toggle on Image and Text panel that allows for decorations to not be affected by camera rotation.

### Alternatives & Workarounds

Right now, you can counterrotate every element every time a camera rotates. This is extremely inefficient however, as it essentially doubles the event count.

### Demo & Mockup

![image (29)](https://user-images.githubusercontent.com/38210271/209466171-d76c1532-c477-446b-8b25-b5296f217244.png)

**Comment by wjdgustn** [comment]
added!
