### ISSUE TITLE
Changing the practice mode settings in custom levels causes the game to forget practice mode is enabled

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [7thbeatgames/adofai#99]
### Please Check

- [X] I searched for the issues, and made sure there were no duplicates.
- [x] I've deleted all the mods and confirmed the issue persists.

### Contact Information

oliverabola@gmail.com, FlameDance#9223

### Summary

In a custom level, if you enable practice mode and change the portion of the level to be practiced or the speed to practice at, the game:

- Will take longer to load practice mode than normal
- Still causes you to start where you selected
- Won't stop you where you selected
- Won't display (Practice mode) on the screen
- Will still change the speed according to your selection
- Will display the normal pause menu, not the practice mode pause menu
- Continues this behavior after pressing restart in the menu, although it will return you to the start of the level
- Does not record your achievement if you complete the level

### Version

v2.3.0 (r100) Mac

### Operating System (OS)

macOS Monterey (M1)

### Platform

Steam

### Device Info

MacBook Pro (14-inch, 2021) with M1 Pro chip

### Steps to Reproduce

1. Enter any custom level
2. Pause the game
3. Select practice
4. Change either the region to practice or the speed of practice
5. See error

### Expected Behavior

The game would behave as it does in main game levels and display (practice mode) on the screen, stop you when you selected, and show the practice mode menu when you pause.

### Observed Behavior

The game does not show (practice mode) or stop you when you selected, and shows the regular pause menu when you pause.

### Reproduction Rate

100%

### Anything else?

[Player.log](https://github.com/7thbeatgames/adofai/files/10309965/Player.log)

https://user-images.githubusercontent.com/100527514/209704006-96855c5a-b80c-4d36-b895-c3593648d845.mp4

(it's hard to tell from the video but the level is slowed down)

**Comment by authop** [comment]
Hello!

Looks like this issue is old! I'd like to close old issues to track relevant issues in the current version. If you are still experiencing these issues, please re-open this issue or write to our Discord server at https://7thbe.at/discord.

Thank you!
